### ISSUE TITLE
3 tests fail

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#2190] opened 2023-07-05 06:58 UTC
### Bug Description

```
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestKrylovSolve.test_10_happy_breakdown_e_ops_none[eigenstate] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <qutip.tests.test_krylovsolve.TestKrylovSolve object at 0xa0f9b8f40>
happy_breakdown_parameters = (Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], 0.5, 0, 1)

    def test_10_happy_breakdown_e_ops_none(self, happy_breakdown_parameters):
        "krylovsolve: check e_ops=None at happy breakdowns"
        psi0, hz, Jx, Jz = happy_breakdown_parameters
        krylov_dim = 12
        N = 4
        dim = 2**N
        H = h_ising_transverse(N, hx=0, hz=hz, Jx=Jx, Jy=0, Jz=Jz)
        tlist = np.linspace(0, 20, 200)
>       self.check_e_ops_none(
            H, psi0, tlist, dim, krylov_dim=krylov_dim
        )

stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:469: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:274: in check_e_ops_none
    krylov_outputs = krylovsolve(H, psi0, tlist, krylov_dim, e_ops=None)
stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:86: in krylovsolve
    _check_inputs(H, psi0, krylov_dim)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

H = Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[-1.  0...0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -5.]]
psi0 = Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
krylov_dim = 12

    def _check_inputs(H, psi0, krylov_dim):
        """Check that the inputs 'H' and 'psi0' have the correct structures."""
        if not isinstance(H, Qobj):
            raise TypeError(
                "krylovsolve currently supports Hamiltonian Qobj operators only"
            )
    
        if not H.isherm:
            raise TypeError("Hamiltonian 'H' must be hermician.")
    
        if not isinstance(psi0, Qobj):
            raise TypeError("'psi0' must be a Qobj.")
    
        if not psi0.isket:
            raise TypeError("Initial state must be a ket Qobj.")
    
        if not ((len(H.shape) == 2) and (H.shape[0] == H.shape[1])):
            raise ValueError("the Hamiltonian must be 2-dimensional square Qobj.")
    
        if not (psi0.dims[0] == H.dims[0]):
>           raise ValueError(
                "'psi0' and the Hamiltonian must share the same dimension."
            )
E           ValueError: 'psi0' and the Hamiltonian must share the same dimension.

stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:453: ValueError

 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_10_happy_breakdown_e_ops_none[eigenstate] ⨯                                   93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_08_check_e_ops_mixed_list[large dim-normal tlist-[c, c]] ✓                    93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_08_check_e_ops_mixed_list[small dim-empty tlist-[c, q]] ✓                     93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_07_check_e_ops_list_single_callable[large dim-empty tlist-[c]] ✓              93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_07_check_e_ops_list_single_callable[intermediate dim-single element tlist-[q]] ✓93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_06_check_e_ops_callable[large dim-single element tlist] ✓                     93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_07_check_e_ops_list_single_callable[small dim-normal tlist-[q]] ✓             93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_07_check_e_ops_list_single_callable[intermediate dim-single element tlist-[c]] ✓93% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_11_happy_breakdown_e_ops_callable[magnetization subspace state XXZ model] ✓   94% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_03_simple_check_states_e_ops_H_ising_transverse ✓                             94% █████████▍
 stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py::TestKrylovSolve.test_05_check_e_ops_none[small dim-normal tlist] ✓                                 94% █████████▍

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestKrylovSolve.test_9_happy_breakdown_simple[eigenstate] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <qutip.tests.test_krylovsolve.TestKrylovSolve object at 0xa0f9b8f10>
happy_breakdown_parameters = (Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], 0.5, 0, 1)

    def test_9_happy_breakdown_simple(self, happy_breakdown_parameters):
        "krylovsolve: check simple at happy breakdowns"
        psi0, hz, Jx, Jz = happy_breakdown_parameters
        krylov_dim = 12
        N = 4
        dim = 2**N
        H = h_ising_transverse(N, hx=0, hz=hz, Jx=Jx, Jy=0, Jz=Jz)
        tlist = np.linspace(0, 20, 200)
>       self.simple_check_states_e_ops(
            H, psi0, tlist, krylov_dim=krylov_dim, square_hamiltonian=False
        )

stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:457: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:217: in simple_check_states_e_ops
    output = krylovsolve(
stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:86: in krylovsolve
    _check_inputs(H, psi0, krylov_dim)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

H = Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[-1.  0...0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -5.]]
psi0 = Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
krylov_dim = 12

    def _check_inputs(H, psi0, krylov_dim):
        """Check that the inputs 'H' and 'psi0' have the correct structures."""
        if not isinstance(H, Qobj):
            raise TypeError(
                "krylovsolve currently supports Hamiltonian Qobj operators only"
            )
    
        if not H.isherm:
            raise TypeError("Hamiltonian 'H' must be hermician.")
    
        if not isinstance(psi0, Qobj):
            raise TypeError("'psi0' must be a Qobj.")
    
        if not psi0.isket:
            raise TypeError("Initial state must be a ket Qobj.")
    
        if not ((len(H.shape) == 2) and (H.shape[0] == H.shape[1])):
            raise ValueError("the Hamiltonian must be 2-dimensional square Qobj.")
    
        if not (psi0.dims[0] == H.dims[0]):
>           raise ValueError(
                "'psi0' and the Hamiltonian must share the same dimension."
            )
E           ValueError: 'psi0' and the Hamiltonian must share the same dimension.

stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:453: ValueError

―――――――――――――――――――――――――――――――――――――――――――――――――――― TestKrylovSolve.test_9_happy_breakdown_simple[magnetization subspace state XXZ model] ――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <qutip.tests.test_krylovsolve.TestKrylovSolve object at 0xa1095afd0>
happy_breakdown_parameters = (Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], 1.0, 1, 0)

    def test_9_happy_breakdown_simple(self, happy_breakdown_parameters):
        "krylovsolve: check simple at happy breakdowns"
        psi0, hz, Jx, Jz = happy_breakdown_parameters
        krylov_dim = 12
        N = 4
        dim = 2**N
        H = h_ising_transverse(N, hx=0, hz=hz, Jx=Jx, Jy=0, Jz=Jz)
        tlist = np.linspace(0, 20, 200)
>       self.simple_check_states_e_ops(
            H, psi0, tlist, krylov_dim=krylov_dim, square_hamiltonian=False
        )

stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:457: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
stage/usr/local/lib/python3.9/site-packages/qutip/tests/test_krylovsolve.py:217: in simple_check_states_e_ops
    output = krylovsolve(
stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:86: in krylovsolve
    _check_inputs(H, psi0, krylov_dim)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

H = Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[ 4.  0...0.  0.  0.  0.  0. -1.  0.  0.  0.  0. -1. -2.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0. -1.  0.  0. -1.  0.  0. -4.]]
psi0 = Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
krylov_dim = 12

    def _check_inputs(H, psi0, krylov_dim):
        """Check that the inputs 'H' and 'psi0' have the correct structures."""
        if not isinstance(H, Qobj):
            raise TypeError(
                "krylovsolve currently supports Hamiltonian Qobj operators only"
            )
    
        if not H.isherm:
            raise TypeError("Hamiltonian 'H' must be hermician.")
    
        if not isinstance(psi0, Qobj):
            raise TypeError("'psi0' must be a Qobj.")
    
        if not psi0.isket:
            raise TypeError("Initial state must be a ket Qobj.")
    
        if not ((len(H.shape) == 2) and (H.shape[0] == H.shape[1])):
            raise ValueError("the Hamiltonian must be 2-dimensional square Qobj.")
    
        if not (psi0.dims[0] == H.dims[0]):
>           raise ValueError(
                "'psi0' and the Hamiltonian must share the same dimension."
            )
E           ValueError: 'psi0' and the Hamiltonian must share the same dimension.

stage/usr/local/lib/python3.9/site-packages/qutip/krylovsolve.py:453: ValueError
```

### Expected Behaviour

n/a

### Your Environment

```shell
QuTip-4.7.2
numpy-1.23.1
Python-3.9
FreeBSD 13.2
```

**Comment by Ericgig** [comment] 2023-07-05 16:15
Hi @yurivict.

Could you give more detail?
I can't reproduce the issue and the error messages are not enough to understand what is happening.

**Comment by hodgestar** [comment] 2023-12-14 22:41
Without more detail we can't help resolve this so closing it for now. Feel free to re-open if you can help debug. Tests pass in quite a few CI combinations.

**Closed by hodgestar** 2023-12-14 22:41 UTC
