### ISSUE TITLE
QuTiP executive error due to update of scipy

### ISSUE THREAD

**Issue by zhangyintai** [qutip/qutip#1019] opened 2019-06-15 08:38 UTC
QuTiP cannot be imported after updating Scipy package to version 1.3.0. 

Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qutip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python36\lib\site-packages\qutip\__init__.py", line 171, in <module>
    from qutip.qobj import *
  File "D:\Python\Python36\lib\site-packages\qutip\qobj.py", line 60, in <module>
    from qutip.fastsparse import fast_csr_matrix, fast_identity
  File "D:\Python\Python36\lib\site-packages\qutip\fastsparse.py", line 37, in <module>
    from scipy.sparse.sputils import (upcast, upcast_char, to_native, isdense, isshape,
ImportError: cannot import name 'IndexMixin'
>>>

I've consulted the problem with the Scipy team and they suggested that:
IndexMixin got moved and changed in gh-7827. It was private though, so QuTiP should not be using it.

So would it be possible to update the QuTiP and to fix this problem? Thanks.

**Comment by nathanshammah** [comment] 2019-06-15 08:49
This issue is a duplicate of #999, #1008 and #1018. It has been addressed by PR 1000.

https://github.com/qutip/qutip/pull/1000. Se discussion in #1018.

**Comment by zhangyintai** [comment] 2019-06-15 10:52
> This issue is a duplicate of #999, #1008 and #1018. It has been addressed by PR 1000.
> 
> #1000. Se discussion in #1018.

Yep, I know that this is caused by the newest version of Siipy. But is there any possibilities to upgrade the qutip. It seems that it is difficult to ask the scipy team to "downgrade" the scipy, isn't it/

**Comment by zhangyintai** [comment] 2019-06-15 10:55
> This issue is a duplicate of #999, #1008 and #1018. It has been addressed by PR 1000.
> 
> #1000. Se discussion in #1018.

But thanks anyway. QuTiP really helps a lot and I'm looking forward to a version that is compatible with the newest scipy.

**Comment by nathanshammah** [comment] 2019-06-15 11:15
You can choose the scipy version to install: `conda install scipy=1.2.1` or `pip install scipy==1.2.1`.

**Comment by ElieGouzien** [comment] 2019-06-18 14:19
This issue has been fixed by #1000, but don't you think there should be a new release of QuTiP to integrate it? A minor release integrating only the corresponding commit could be enough.

There is nothing more frustrating for a beginner when following the installation instructions fails. I can grantee that most QuTiP users are not expert of packages dependencies and follow installation instructions without understanding them.

**Comment by nathanshammah** [comment] 2019-06-19 00:07
Agreed. We’re working on a release soon.

**Comment by nathanshammah** [comment] 2019-07-12 13:46
@ElieGouzien the new QuTiP release solves this. See the [change log](http://qutip.org/docs/latest/changelog.html) for more information on new features.

**Closed by nathanshammah** 2019-07-12 13:46 UTC
