### ISSUE TITLE
Time dependent Hamiltonian

### ISSUE THREAD

**Issue by sankart12** [qutip/qutip#2026] opened 2022-11-28 23:21 UTC
I am trying to solve the following type of  problem with time-dependent Hamiltonian; 

H = H_0 - f(t) H_1
f(t) = $ A exp(-(t/sigma)^2) $

# When A is constant, the usual thing to do is

```
def H1_coeff(t, args):
        A = args['A']
        sig = args['sigma']
        return A * np.exp(-(t/sig)**2)

H = [H0, [H1, H1_coeff]]
args = {'A': 9, 'sigma': 5}

result = mesolve( H, psi0, t, [], e_ops, args = args)
```

# I am trying to solve a problem where A is a list

```
A = [1, 3, 5, 7, 9]
```
# How do I implement **"mesolve**" to get the final_states in this case?

**Comment by Ericgig** [comment] 2022-11-28 23:46
Please use the [help group](https://groups.google.com/g/qutip) when the issue is not a bug or feature request.

If you want the evolution with different values of a parameter, you need to call `mesolve` in a loop, we don't have a way to merge the calls:
```
final_states = [
    mesolve(H, psi0, t, [], e_ops, 
        args={'A': A, 'sigma': 5}, 
        options=Options("store_final_state": True).final_state
    for A in [1, 3, 5, 7, 9]
]
```

**Comment by sankart12** [comment] 2022-11-30 19:53
Thank you, Eric. It works. 
So then this gives me the final_states as a function of time for each A in the list.

One follow-up question.
I want to extract the final_states as a function of A at a particular time. How should I code this?

**Comment by Ericgig** [comment] 2022-11-30 22:19
`result.state` will return the state for all times in ``t``.

**Comment by sankart12** [comment] 2022-12-01 06:50
Hi,

Sorry that I wasn't specific enough ( or perhaps articulate enough) about my question. 
Here's what I wanted to ask.

![Screenshot (88)](https://user-images.githubusercontent.com/87878979/204981224-2c018b3f-9f65-44ad-ae75-08ae112a6a73.png)

```
delta = [1,2, 3,5, 6, 7, 8, 9]
omega = 3
t= np.linspace(0, 10, 100)

def H1_coeff(t, args):
        delta = args['delta']
        omega = args['omega']
        return np.exp(1j * (omega - delta) *t)

H = [H0, [H1, H1_coeff], [H2, H2_coeff]]
args = {'delta': delta, 'omega': omega}

opt = Options()
opt.store_final_state = True
result = [
mesolve( H, psi0, t, [], [], args = {'delta': delta, 'omega': omega}, options = opt) ) 
for delta in delta 
]
```

```
# #when I do

result[0].states

## I get the states for **delta = 1**, (in the list delta above) at all times.
## and similarly for other values of delta.

## Is there a way to write **H1_coeff** or **mesolve** so as to find states at one particular **instant of time **
## (say t = 10) for all deltas in the list.
```

**Comment by Ericgig** [comment] 2022-12-01 13:58
No, `mesolve` does not loop over `args`. 
You can obtain the list over deltas from `result`, but it's now a python list manipulation question, not a qutip question.

Github issues are for bug report or feature request.
It is now a python question, not a qutip question and I don't want to encourage it's use as a helpdesk so I am closing this.

**Closed by Ericgig** 2022-12-01 13:58 UTC
