### ISSUE TITLE
ODE Integration Error in Tutorial Code

### ISSUE THREAD

**Issue by lzawbrito** [qutip/qutip#1896] opened 2022-05-19 05:55 UTC
### Bug Description

I have been running into an issue similar to #806, #1605, and #1623 wherein usage of `mesolve` produces the attached error.

It seems as if the majority of the users that reported that error had some suspect input parameters leading to slow convergence in integration; to confirm that this wasn't the case I tried running the [qubit dynamics QuTiP tutorial](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/qubit-dynamics.ipynb), which _still_ produced the same error.

My system specs are as follows: `21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64`. My package installations can be found here: [requirements.txt](https://github.com/qutip/qutip/files/8725390/requirements.txt). These are also listed in the below categories.

Any help would be appreciated.

### Code to Reproduce the Bug

```shell
import matplotlib.pyplot as plt
import numpy as np
from qutip import *
def qubit_integrate(epsilon, delta, g1, g2, solver):

    H = epsilon / 2.0 * sigmaz() + delta / 2.0 * sigmax()
        
    # collapse operators
    c_ops = []

    if g1 > 0.0:
        c_ops.append(np.sqrt(g1) * sigmam())

    if g2 > 0.0:
        c_ops.append(np.sqrt(g2) * sigmaz())

    e_ops = [sigmax(), sigmay(), sigmaz()]
        
    if solver == "me":
        output = mesolve(H, psi0, tlist, c_ops, e_ops)  
    elif solver == "es":
        output = essolve(H, psi0, tlist, c_ops, e_ops)  
    elif solver == "mc":
        ntraj = 250
        output = mcsolve(H, psi0, tlist, ntraj, c_ops, [sigmax(), sigmay(), sigmaz()])  
    else:
        raise ValueError("unknown solver")
        
    return output.expect[0], output.expect[1], output.expect[2]
epsilon = 0.0 * 2 * np.pi   # cavity frequency
delta   = 1.0 * 2 * np.pi   # atom frequency
g2 = 0.15
g1 = 0.0

# intial state
psi0 = basis(2,0)

tlist = np.linspace(0,5,200)

# analytics
sx_analytic = np.zeros(shape(tlist))
sy_analytic = -np.sin(2*np.pi*tlist) * np.exp(-tlist * g2)
sz_analytic = np.cos(2*np.pi*tlist) * np.exp(-tlist * g2)
sx1, sy1, sz1 = qubit_integrate(epsilon, delta, g1, g2, "me")
```

### Code Output

```shell
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb Cell 8' in <cell line: 1>()
----> [1](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000007?line=0) sx1, sy1, sz1 = qubit_integrate(epsilon, delta, g1, g2, "me")

/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb Cell 6' in qubit_integrate(epsilon, delta, g1, g2, solver)
     [14](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000005?line=13) e_ops = [sigmax(), sigmay(), sigmaz()]
     [16](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000005?line=15) if solver == "me":
---> [17](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000005?line=16)     output = mesolve(H, psi0, tlist, c_ops, e_ops)  
     [18](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000005?line=17) elif solver == "es":
     [19](vscode-notebook-cell:/Users/lzawbrito/projects/PULSEE/demos/qubit-dynamics.ipynb#ch0000005?line=18)     output = essolve(H, psi0, tlist, c_ops, e_ops)  

File ~/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py:244, in mesolve(H, rho0, tlist, c_ops, e_ops, args, options, progress_bar, _safe_mode)
    [241](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=240)     v = rho0.full().ravel('F')
    [242](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=241)     func(0., v, *ode_args) + v
--> [244](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=243) res = _generic_ode_solve(func, ode_args, rho0, tlist, e_ops, options,
    [245](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=244)                          progress_bar, dims=rho0.dims)
    [246](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=245) res.num_collapse = len(c_ops)
    [248](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=247) if e_ops_dict:

File ~/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py:496, in _generic_ode_solve(func, ode_args, rho0, tlist, e_ops, opt, progress_bar, dims)
    [493](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=492) progress_bar.update(t_idx)
    [495](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=494) if not r.successful():
--> [496](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=495)     raise Exception("ODE integration error: Try to increase "
    [497](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=496)                     "the allowed number of substeps by increasing "
    [498](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=497)                     "the nsteps parameter in the Options class.")
    [500](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=499) if opt.store_states or expt_callback:
    [501](file:///Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip/mesolve.py?line=500)     cdata = get_curr_state_data(r)

Exception: ODE integration error: Try to increase the allowed number of substeps by increasing the nsteps parameter in the Options class.
```

### Expected Behaviour

The evolution should have reproduced the result given in the tutorial notebook.

### Your Environment

```shell
QuTiP Version:      4.7.0
Numpy Version:      1.21.1
Scipy Version:      1.7.3
Cython Version:     None
Matplotlib Version: 3.5.0
Python Version:     3.9.0
Number of CPUs:     8
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
Installation path:  /Users/lzawbrito/miniforge3/envs/pulsee/lib/python3.9/site-packages/qutip
```

**Comment by christian512** [comment] 2022-05-26 16:51
Hey @lzawbrito, 
I tried to reproduce your error on a Linux (Ubuntu) machine. I installed your exact environment (all versions equal) and your provided code runs without a problem. Also the notebook you refer to does not give an error. So it seems to me that it is a problem with macOS. 

Did you try to increase `nsteps`? You can do so by adding an option to the `mesolve()` function: 

`output = mesolve(H, psi0, tlist, c_ops, e_ops, options=Options(nsteps=1000))`

Let me know if experimenting with the nsteps works!

**Comment by lzawbrito** [comment] 2022-05-28 17:56
Hi @christian512, thanks for the help! I've increased `nsteps` for that particular simulation and the integration runs fine without any errors. One caveat is I have not checked the correctness of the result. 

On the other hand, as soon as I tried `mesolve` on a simple Larmor precession problem, `mesolve` started either (1) throwing the typical ODE integration error or (2) integrating but producing a manifestly incorrect result (the final state is not on the Bloch sphere).

The code I am using is 
```
from qutip import * 
import numpy as np

sz = sigmaz()

init_ket = 2 ** (-1/2) * Qobj([[1], [1]]) # Bloch vector is unit x
init_dm = init_ket * init_ket.dag()

b_0 = 1
gam = 1
h_zeem = gam * b_0 * sz
h = [h_zeem]

larmor_freq = gam * b_0 
period = 2 * np.pi / (larmor_freq)
t = np.linspace(0, period / 2, 100)

print(mesolve(h, init_dm, t, options=Options(nsteps=1e6)).states[-1])
```

Which produces 
```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[   0.5        +0.j         -263.5988765-267.24047092j]
 [  -2.1425229  +0.49907152j    0.5        +0.j        ]]
```

**Comment by christian512** [comment] 2022-05-29 11:25
Hi @lzawbrito, I guess that choosing `nsteps=1e6` is a pretty big value and that it leads to problems in the ODE integration. However, again running on my system, I get a reasonable output even with these high `nsteps`: 

``` 
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5       +0.00000000e+00j 0.49999938-4.02511613e-06j]
 [0.49999938+4.02511613e-06j 0.5       +0.00000000e+00j]]
```  
I guess that this is a problem with SciPy's integrator and your system.  I don't have enough experience with QuTiP to give a more detailed analysis. Maybe someone else knows about this? @BoxiLi

**Comment by BoxiLi** [comment] 2022-05-29 12:32
I cannot reproduce this on either Ubuntu or Windows...

`nstep` only sets the maximally allowed number of time steps. That exception is a quite general one. It only says that the ODE integrator fails. But the Larmor example is really a trivial one and if it fails then something very important must have been contaminated.

If resinstalling in a fresh environment does not work, I can only suggest to debug at the scipy level.

**Comment by hodgestar** [comment] 2022-12-10 16:39
Closing since this is no reproducible currently. Please re-open or reply if this is still an issue.

**Closed by hodgestar** 2022-12-10 16:39 UTC
