### ISSUE TITLE
Unstable `qutip.testing.run()` prompts abort traps locally (Mac, Python 3.7)

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1160] opened 2020-01-18 02:58 UTC
On my Mac (Mojave 10.14.5) the latest development version of qutip tests can fail at different points. 

First, I run into an abort trap at ptrace. 

Then, upon another run, I bumped into this other abort trap error 
```
tests/test_superop_reps.py::TestSuperopReps::test_ChoiKrausChoi Fatal Python error: Aborted

Current thread 0x000000010b9155c0 (most recent call first):
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/qutip-4.5.0.dev0+d13f5435-py3.7-macosx-10.9-x86_64.egg/qutip/superop_reps.py", line 547 in to_kraus
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/qutip-4.5.0.dev0+d13f5435-py3.7-macosx-10.9-x86_64.egg/qutip/tests/test_superop_reps.py", line 106 in test_ChoiKrausChoi
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/python.py", line 166 in pytest_pyfunc_call
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/python.py", line 1435 in runtest
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 131 in pytest_runtest_call
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 207 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 234 in from_call
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 207 in call_runtest_hook
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 182 in call_and_report
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 96 in runtestprotocol
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/runner.py", line 81 in pytest_runtest_protocol
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/main.py", line 270 in pytest_runtestloop
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/main.py", line 246 in _main
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/main.py", line 196 in wrap_session
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/main.py", line 239 in pytest_cmdline_main
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92 in main
  File "/miniconda3/envs/qutipdev45/lib/python3.7/site-packages/qutip-4.5.0.dev0+d13f5435-py3.7-macosx-10.9-x86_64.egg/qutip/testing.py", line 45 in run
  File "<stdin>", line 1 in <module>
Abort trap: 6
```
This is in a conda environment with qutip development version with 
```
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
```
and 
```
QuTiP Version:      4.5.0.dev0+d13f5435
Numpy Version:      1.17.2
Scipy Version:      1.3.1
Cython Version:     0.29.13
Matplotlib Version: 3.1.1
Python Version:     3.7.4
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
Installation path:  /miniconda3/envs/qutipdev45/lib/python3.7/site-packages/qutip-4.5.0.dev0+d13f5435-py3.7-macosx-10.9-x86_64.egg/qutip
```

**Comment by nathanshammah** [comment] 2020-01-18 03:17
Upon a third run, tests ran fine, and then the bug found in #1158 occurred.

**Comment by jakelishman** [comment] 2021-04-15 11:38
There is a chance that this is the same bug as #1495, which has a fix posited in #1498 - it matches all the versioning criteria, though on that issue we hadn't detected a problem with this particular test at these dimensions.

**Comment by jakelishman** [comment] 2021-04-24 14:14
This segfault is still _very_ occasionally present on Mac as of QuTiP 4.6.0 and the current master (624405e7).  Unfortunately, I've not been able to find any sort of reliable reproducer, so I can't offer a huge amount of insight into what might be causing it.  Here's an example output:
```
jake@tauros$ pytest tests/test_superop_reps.py
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jake/code/qutip/qutip/qutip/tests, configfile: pytest.ini
plugins: rerunfailures-9.1.1
collected 15 items

tests/test_superop_reps.py ..F............                                                                                                                                                           [100%]

================================================================================================= FAILURES =================================================================================================
____________________________________________________________________________________ TestSuperopReps.test_ChoiKrausChoi ____________________________________________________________________________________

self = <qutip.tests.test_superop_reps.TestSuperopReps object at 0x11f1140d0>

Fatal Python error: Segmentation fault

Current thread 0x000000010c77b5c0 (most recent call first):
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/sre_compile.py", line 312 in _optimize_charset
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/sre_compile.py", line 120 in _compile
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/sre_compile.py", line 607 in _code
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/sre_compile.py", line 768 in compile
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/re.py", line 304 in _compile
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/re.py", line 252 in compile
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 424 in _process_regex
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 495 in _process_state
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 479 in _process_state
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 479 in _process_state
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 516 in process_tokendef
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pygments/lexer.py", line 577 in __call__
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_io/terminalwriter.py", line 208 in _highlight
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_io/terminalwriter.py", line 192 in _write_source
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_code/code.py", line 1101 in _write_entry_lines
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_code/code.py", line 1119 in toterminal
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_code/code.py", line 1025 in toterminal
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/_code/code.py", line 995 in toterminal
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/reports.py", line 87 in toterminal
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/terminal.py", line 1030 in _outrep_summary
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/terminal.py", line 1011 in summary_failures
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/terminal.py", line 828 in pytest_terminal_summary
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/callers.py", line 182 in _multicall
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/terminal.py", line 813 in pytest_sessionfinish
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/callers.py", line 203 in _multicall
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/main.py", line 304 in wrap_session
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/Users/jake/.anaconda3/envs/qutip-dev/bin/pytest", line 11 in <module>
Segmentation fault: 11
```

This was done with commit 624405e7, SciPy 1.6.2 and Numpy 1.19.5.  My BLAS version has chopped and changed an awful lot, but I believe that run was with netlib (reference) implementations.  The "random" stack trace from pytest looks to me like the error came about during garbage collection, and I really don't imagine pytest is to blame.

We have in the past had issues with some bad calls in SciPy linalg functions, so it's _possible_ that they are the cause again, but I doubt it; we'd expect the stack traces to reliably show scipy to be the problem in that case.

I wasn't able to reproduce this segfault on Windows, but that doesn't mean a huge amount, because I also can't reliably reproduce it on Mac.

I suspect that the cause is some dodgy handling of pointers in the `struct CSR_Matrix` type in `qutip/cy/sparse_routines.pxi`, but this is just a suspicion.  As far as I remember, I have _never_ seen this segfault when using the `dev.major` branch, which completely removes `CSR_Matrix` and replaces it with a much more robust Cython `CSR` type, which adds to my suspicion, but again, because the reproducer is unreliable, I cannot be sure.  I have tried running these failing tests through valgrind before, but unfortunately to no avail.

**Comment by jakelishman** [comment] 2021-04-24 14:25
Note that the above reproducer uses Python 3.8, so this is not just limited to Python 3.7.  This is potentially an important note, because 3.8 minorly changed how `Py_malloc` is handled in builds.

**Comment by jakelishman** [comment] 2021-04-24 17:19
Ok, I think I may have some more information.  I am fairly sure that this is the same bug as #1120, #963 and #944 (which I believe was not actually ever fixed).  I'm going to put the information here.

My working theory is currently that this is a MKL bug on Mac.

For posterity, let me just dump out some information.

## Things you should know if you've not worked with segfaults before

- `Abort trap 6`, `Segmentation fault` and a few other points can all be from the same cause
- Segmentation faults are typically caused by reading or writing to memory that isn't owned by our process.  These often occur by reading/writing too much data to an allocated pointer, or trying to read/write a memory location where the location was read from uninitialised memory.
- Segfaults will not always reliably occur.  It's _very_ difficult to prove that swapping tools "fixes" a segfault; it can often just move around enough allocations to mask the problem, not fix it.
- Python stack traces are likely to be almost entirely unreliable in these cases, because the segfault may often occur while the garbage collector is running, and that will happen at seemingly non-deterministic times.
- Running files in a slightly different interpreter, running within a test runner with differing numbers of files, doing different work before and after will all cause the segfault to change, and may mask it.
- As annoying as they are, segfaults are actually the _good_ case of the bug - the worst is when we have invalid memory writes but _no_ segfault, because then we have memory corruption that's gone undetected.


## Thoughts about #1120

This issue is still present using Andrew's `Malloc.py` file as of the current master branch (commit 624405e7), and is in QuTiP 4.6.0 and most previous versions.  I have been able to reproduce the segfaults with Python 3.7, but not Python 3.8, and I can reproduce it with all allowable values of `PYTHONMALLOC`.  The most telling is `pymalloc_debug`, where the entire operation completes (it prints "500"), and _then_ the fault occurs.  This along with the error message should hopefully make it clear that an out-of-bounds write occurs occasionally, and it is temperamental where exactly this happens.

This is typically not detected until the object is freed, when the Python allocators do a little bit of checksumming.  I think that in _all_ cases we're seeing the failure come from the garbage collection, but I can't be 100% certain - note that this almost certainly means the failure is somewhere completely different, and it's only _detected_ at garbage collection.

Here is the output of a Python 3.8 crash on the `Malloc.py` file with some additional debugging enabled.  This is with Python 3.8.8, Numpy 1.19.2, Scipy 1.6.2 and MKL:
```
jake@tauros$ PYTHONMALLOC=pymalloc_debug python -Xfaulthandler Malloc.py
500
Debug memory block at address p=0x7fa2e02de610: API 'r'
    61503 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x7fa2e02ed64f are not all FORBIDDENBYTE (0xfd):
        at tail+0: 0x00 *** OUCH
        at tail+1: 0x00 *** OUCH
        at tail+2: 0x00 *** OUCH
        at tail+3: 0x00 *** OUCH
        at tail+4: 0x00 *** OUCH
        at tail+5: 0x00 *** OUCH
        at tail+6: 0x00 *** OUCH
        at tail+7: 0x00 *** OUCH
    Data at p: dd dd dd dd dd dd dd dd ... 00 00 00 00 00 00 00 00

Enable tracemalloc to get the memory block allocation traceback

Fatal Python error: bad trailing pad byte
Python runtime state: finalizing (tstate=0x7fa2ddc04270)

Current thread 0x00000001123d55c0 (most recent call first):
<no Python frame>
Abort trap: 6
```

## Relation to `to_kraus`

The above `Malloc.py` file uses `scipy.linalg.eig` via use of an `eseries` version of `correlation`.  The current test of superoperator representations uses `choi_to_kraus` which also calls `scipy.linalg.eig`.  Here is a file `kraus.py` that can  reproduce these segfaults semi-reliably (may need to run it a few times to get it to trigger):

```python
import qutip

s = qutip.rand_super()
c = qutip.to_choi(s)
k = qutip.to_kraus(c)
```

For example, here's a similar command on this file:

```
Debug memory block at address p=0x7f98cc467db0: API 'r'
    61503 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x7f98cc476def are not all FORBIDDENBYTE (0xfd):
        at tail+0: 0x00 *** OUCH
        at tail+1: 0x00 *** OUCH
        at tail+2: 0x00 *** OUCH
        at tail+3: 0x00 *** OUCH
        at tail+4: 0x00 *** OUCH
        at tail+5: 0x00 *** OUCH
        at tail+6: 0x00 *** OUCH
        at tail+7: 0x00 *** OUCH
    Data at p: dd dd dd dd dd dd dd dd ... 00 00 00 00 00 00 00 00

Enable tracemalloc to get the memory block allocation traceback

Fatal Python error: bad trailing pad byte
Python runtime state: finalizing (tstate=0x7f98c9d018e0)

Current thread 0x0000000109fe85c0 (most recent call first):
<no Python frame>
Abort trap: 6
```

So these both use `scipy.linalg.eig`, which is suspicious.


## Valgrind checks

To see if I could track it down, I had a go with valgrind.  This isn't guaranteed to find everything, because I'm not using a debug build of Python, and Python also typically optimises small allocations by using a custom allocator into some pre-allocated space it manages itself - invalid writes that still fall within this may not get detected by valgrind.

Here is the output of `valgrind` running on the `kraus.py` file I wrote in the previous section: [kraus_valgrind.txt](https://github.com/qutip/qutip/files/6370180/kraus_valgrind.txt) (note I filtered out like 30,000 errors that stem from Python's internal memory management - they're nothing to worry about, they're just what happens when you have your own allocator).  The important part is

```
==54133== Invalid write of size 8
==54133==    at 0x10AFAFA8A: ??? (in /Users/jake/.anaconda3/envs/py38/lib/libmkl_intel_thread.dylib)
==54133==    by 0xFFFFFFFF: ???
==54133==    by 0x1162E4DEF: ???
==54133==    by 0x1162E3A5F: ???
==54133==    by 0x10550EB3F: ???
==54133==    by 0x3FEFFFFFFFFFFFFF: ???
```

Obviously I don't have the debugging symbols for MKL, so it's pretty hard to say where exactly it's coming from, but it is at least clearly inside that library.  I ran `valgrind` on the `Malloc.py` file above, and get the exact same invalid write, which is promising.

So the most likely public Python call is `scipy.linalg.eig`.


## Minimal reproducer

Ok, so now let me cut it down to a minimum `eig.py`:

```python
import numpy as np
import scipy.linalg

x = np.random.rand(25, 25) + 1j*np.random.rand(25, 25)
scipy.linalg.eig(x)
```

Note that this filjake@tauros$ PYTHONMALLOC=pymalloc_debug python -Xfaulthandler,tracemalloc eig.py
python(54517,0x10a5505c0) malloc: Incorrect checksum for freed object 0x7fe6cb4150e0: probably modified after being freed.
Corrupt value: 0x3ff0000000000000
python(54517,0x10a5505c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
e does not even use `qutip`.  You can run `PYTHONMALLOC=pymalloc_debug python -Xfaulthandler,tracemalloc eig.py`, and it will occasionally trigger a segfault (it happens to me about 1 in 5 times).  It's not always the same message as above, e.g.:
```
jake@tauros$ PYTHONMALLOC=pymalloc_debug python -Xfaulthandler,tracemalloc eig.py
python(54517,0x10a5505c0) malloc: Incorrect checksum for freed object 0x7fe6cb4150e0: probably modified after being freed.
Corrupt value: 0x3ff0000000000000
python(54517,0x10a5505c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

However if I run it within valgrind:
```
jake@tauros$ valgrind --suppressions=valgrind-python.supp python -Xfaulthandler eig.py
==54530== Memcheck, a memory error detector
==54530== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==54530== Using Valgrind-3.17.0.GIT-lbmacos and LibVEX; rerun with -h for copyright info
==54530== Command: python -Xfaulthandler eig.py
==54530==
==54530== Invalid write of size 8
==54530==    at 0x10ABF7A8A: ??? (in /Users/jake/.anaconda3/envs/py38/lib/libmkl_intel_thread.dylib)
==54530==    by 0xFFFFFFFF: ???
==54530==    by 0x103124AFF: ???
==54530==    by 0x10312376F: ???
==54530==    by 0x10550F0BF: ???
==54530==    by 0x3FEFFFFFFFFFFFFF: ???
```
the exact same.


## Further steps

I'm now reasonably convinced that this isn't directly an issue with QuTiP.  I suspect it isn't an issue with `scipy` either, but I'm not sure - it looks like a slight overwrite in MKL on macOS, though it's also possible that `scipy` passes some invalid pointers when dropping down to BLAS/LAPACK.

I get the impression that the next steps involve dropping down a level of abstraction, down to Cython to directly call scipy's wrappers, or even fully down to C and link directly against MKL.  I _may_ have a look in the future, but I've had enough of it today for sure.

**Comment by hodgestar** [comment] 2021-11-15 11:58
See also #1694 and https://github.com/numpy/numpy/issues/20356 for further issues with MKL on numpy.

**Comment by hodgestar** [comment] 2022-05-17 14:59
I'm closing this because the minimal reproducer doesn't involve QuTiP and because we've already reported some MKL issues to numpy. If there is more to do here, I suspect it is opening and issue with numpy and hoping the maintainers here have enough knowledge / desire to help dig further.

**Closed by hodgestar** 2022-05-17 14:59 UTC
Labels: code, unitaryhack
