### ISSUE TITLE
Finding Kraus Operator from non hermitian Process Matrix

### ISSUE THREAD

**Issue by apassenger** [qutip/qutip#1799] opened 2022-02-08 11:12 UTC
I have my process matrix which is produced by experiment. Since the environment has noise and imperfections, my process matrix is not hermitian. I am trying to find my kraus operators by `to_kraus` ,`super_to_kraus` `choi_to_kraus`. Each time I found the same kraus operators but I cannot find my process matrix from kraus operators. 

Here is the explanation what I did exactly
1) Kraus operators was found from ideal process matrices correctly (with to_kraus function)
2) kraus_to_super function could find process matrix from kraus operators for ideal kraus operators
3) Kraus operators from real process matrix was found by to_kraus function
4) I computed process matrix by the formula (kraus0*rho_free*kraus0.conj().T + kraus1*rho_free*kraus1.conj().T +... ) and computed by the function kraus_to_super and the results are exactly the same but not equal to process matrix
5) I computed choi matrix and then kraus operators. These kraus operators are exactly the same as what I found from the to_kraus function. so I can't find the process matrix from kraus operators but I can find the process matrix from the choi matrix!
6) I computed the choi matrix and found the eigenvectors of the choi matrix. I converted them to 2*2 matrices. I found the mapping by hand and by the function the result is same but not same with the process matrix

So could someone explain what is the procedure to compute kraus operators correctly for non hermitian process matrix in qutip?

**Comment by hodgestar** [comment] 2022-02-08 14:39
@apassenger Thank you for posting your question. Since this is a "am I using QuTiP correctly" question and not a bug report, I would suggest posting it to the mailing list https://groups.google.com/g/qutip instead where more people will see it.

Do you have a small code snippet you could share that illustrates the problem you're encountering?

**Comment by apassenger** [comment] 2022-02-08 23:40
Sure, I am explaning with code:
Here is the process matrix

```
process = array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.001,  0.986,  0.02 ,  0.04 ],
       [ 0.014,  0.01 ,  0.019, -0.957],
       [-0.028, -0.031,  0.949,  0.008]])

```
I first convert it to a Qobj with this script:

```
s_process = qutip.Qobj(process, type='super')
    kraus = qutip.to_kraus(s_process)
    kraus

```
I found my kraus operators. Now I want to check if the kraus operators are good or not. So I used this code:

```
back = qutip.kraus_to_super(kraus)
 back
```
And I got this irrelevant matrix:

```
[[ 0.324+0.j -0.269+0.j -0.269-0.j  0.498+0.j]
 [ 0.257+0.j  0.294-0.j -0.485-0.j -0.243+0.j]
 [ 0.257-0.j -0.485+0.j  0.294+0.j -0.243-0.j]
 [ 0.48 +0.j  0.243-0.j  0.243+0.j  0.291+0.j]]
```
I also cheked if the sum of kraus operator(I multiplied the kraus operators with their conj.T and then summed) is equal to identity or not with. And it is not identity too

Then I tried to conver my process matrix to choi matrix and then found the kraus operators with these formula:

   ```
 s_process = qutip.Qobj(process, type='super')
    choi = qutip.to_choi(s_process)
    kraus = qutip.choi_to_kraus(choi)
    kraus
```
I got the same kraus operaotors but again I cannot have my intiial process amtrix from these kraus operators.
It is probably because of hermicity problem. Because I do not have an hermitian operator since we have noise in the real system. So I wonder if qutip have a way to find kraus operator for non hermitian matrix. I did not write to google groups because I saw that the last post posted a few years ago. So I decided to write here

**Comment by apassenger** [comment] 2022-02-11 03:07
any answer/update?
Thanks

**Comment by Ericgig** [comment] 2024-04-01 04:03
Closing, hopefully this was discussed and answered in the google group.

**Closed by Ericgig** 2024-04-01 04:03 UTC
