### ISSUE TITLE
install qutip on windows10 with some problems

### ISSUE THREAD

**Issue by saiyagami** [qutip/qutip#1079] opened 2019-08-31 15:25 UTC
I had tried many times to install the anaconda3.5 3.6 and 3.7, for installing qutip 4.4.0or4.4.1. But when I verifying the Installation, some similar errors always occur, as indicated below
![QQ截图20190831230327](https://user-images.githubusercontent.com/54746315/64065880-d92e2300-cc45-11e9-9672-f13fca2ffb36.png)
ps: I have install vs2015 and option for c++ compiler
in addition, there are some installation information as below
![QQ截图20190831224652](https://user-images.githubusercontent.com/54746315/64065902-26aa9000-cc46-11e9-9c60-6796fc1deff7.png)
the red underline has indicated some problem, is it matter?
who can give some advice for dealing with it? 
Thanks a lot

**Comment by Ericgig** [comment] 2019-09-03 20:22
4.4.1 should correct this bug.
Could you try reinstalling.

**Comment by saiyagami** [comment] 2019-09-04 00:35
actually, I had installed the 4.4.1 firstly, but it had always a similar problem. have you had other advice?

**Comment by tehruhn** [comment] 2019-10-09 06:47
Hi @saiyagami , your errors seem to be centered around OpenMP and parallelization stuff. It seems from the red underlined error that you do not have OpenMP installed, which shouldn't be the case since it is bundled with the Visual C/C++ compiler by default.

I'd recommend you try the following, in this order:
1. Try running the install again using the cloned repository's `setup.py` file, but this time run it as `python setup.py install --with-openmp`. Hopefully this configures things properly, and you don't see any more OpenMP related errors.
2. If the above doesn't work, that suggests a more pathological error, in which case you probably should try using another compiler such as MinGW. Should you do so, please find more detailed instructions [https://stackoverflow.com/questions/11079586/getting-started-with-openmp-install-on-windows](here).

**Comment by Ericgig** [comment] 2019-10-09 14:33
Hi @tehruhn, Openmp is not needed to run Qutip in parrallel. We are using the module multiprocessing. 
The 4.4.0 error is an error on my part. The 4.4.1 error seems to comes from temp files being erased too quickly for windows version of multiprocessing. 
multiprocessing does not use shared memory and reload all libraries from the files. string based coefficient are written to file as importable libraries and imported at runtime. In 4.4.1 once imported the file is immediately erased. Work file on linux, but I believe this is the cause of the error on windows. My PR #1082 keep the files until the object using it is no longer used, I am hoping this solve the problem.

**Comment by nathanshammah** [comment] 2019-11-27 08:46
Should by closed by #1082. Reopen if necessary.

**Closed by nathanshammah** 2019-11-27 08:46 UTC
