### ISSUE TITLE
QuTiP install for latest Python (3.9) on fresh conda env fails

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip#1371] opened 2020-10-18 13:24 UTC
@tehruhn and I found that trying to install qutip from pip with the latest python 3.9 fails. When we run the installations from a fresh conda env (conda 4.8.5) using pip as

```
pip install qutip
```
or with conda (using both)

```
conda install -c conda-forge qutip
conda install qutip
```

we get different errors. The errors do not occur if we use python3.8 while creating the conda environment as

```
conda create -n py38 python==3.8
```

Looking at the error it seems there is specification that prohibits python 3.9. @jakelishman @Ericgig any idea  about this?

# Steps to reproduce (with conda 4.8.5)

```
conda create -n qutip-test python=3.9
conda activate qutip-test
conda install -c conda-forge qutip
```

### Error
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - qutip -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.


Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by jakelishman** [comment] 2020-10-18 13:33
`qutip` has binary built extensions and we distribute binary releases through `conda`.  These generally have to be built against a specific version of CPython, so we haven't released a cp39 candidate package yet, and `conda` will recognise that as effectively a requirement that `python<3.9`.

`pip` should install from source, because we haven't yet built wheels to distribute that way (though I've been looking into that a bit more recently), so the error will likely be completely different - what sort of error do you get from that?

**Comment by jakelishman** [comment] 2021-03-29 11:27
Closing this now, unless you have more problems - QuTiP has binary release candidates for 4.5.2 and 4.5.3 on `conda-forge` (I think they rebuilt 4.5.2 since this issue), and I couldn't reproduce any build failures on `pip` with 3.9.

**Closed by jakelishman** 2021-03-29 11:27 UTC
