### ISSUE TITLE
"pip3 install quitp" fails unless cython is already installed

### ISSUE THREAD

**Issue by jevonlongdell** [qutip/qutip#1246] opened 2020-05-03 23:00 UTC
**Describe the bug**
It looks like the pypi package doesn't have cython as a dependency?

**To Reproduce**
Do a "pip3 install cython" on a fresh ubuntu 20.04 install (i had already installed numpy and scipy)

** This is what happens when I try it**
jevon@bb8:~$ pip3 install qutip
Collecting qutip
  Downloading qutip-4.5.0.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 509 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-69anjthq/qutip/setup.py'"'"'; __file__='"'"'/tmp/pip-install-69anjthq/qutip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-69anjthq/qutip/pip-egg-info
         cwd: /tmp/pip-install-69anjthq/qutip/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-69anjthq/qutip/setup.py", line 52, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

** Installing cython fixes it **

jevon@bb8:~$ pip3 install cython
Collecting cython
  Downloading Cython-0.29.17-cp38-cp38-manylinux1_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 721 kB/s 
Installing collected packages: cython
Successfully installed cython-0.29.17
jevon@bb8:~$ pip3 install qutip
Collecting qutip
  Using cached qutip-4.5.0.tar.gz (3.5 MB)
Requirement already satisfied: cython>=0.21 in ./.local/lib/python3.8/site-packages (from qutip) (0.29.17)
Requirement already satisfied: numpy>=1.12 in ./.local/lib/python3.8/site-packages (from qutip) (1.18.3)
Requirement already satisfied: scipy>=1.0 in ./.local/lib/python3.8/site-packages (from qutip) (1.4.1)
Building wheels for collected packages: qutip
  Building wheel for qutip (setup.py) ... done
  Created wheel for qutip: filename=qutip-4.5.0-cp38-cp38-linux_x86_64.whl size=17905114 sha256=3f461cbc07b40c0de96b709ea20bca495c7ffe1b6060a533a1ab733107c161ab
  Stored in directory: /home/jevon/.cache/pip/wheels/3a/4d/bf/1c8e9f7874f26a6510d78790d3ba518c98e674e5771110fe1e
Successfully built qutip
Installing collected packages: qutip
Successfully installed qutip-4.5.0

**Comment by willsALMANJ** [comment] 2020-05-15 19:44
I think might be solved by adding a `pyproject.toml` file with something like:

    [build-system]
    requires = ["setuptools", "wheel", "Cython"]

as suggested in [the Cython documentation](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#basic-setup-py).

**Comment by gschaffner** [comment] 2020-07-02 03:22
I think that this is a duplicate of #1174 and #739.

**Comment by BoxiLi** [comment] 2020-07-25 07:09
Closed by #1309

**Closed by BoxiLi** 2020-07-25 07:09 UTC
Labels: BUG
