### ISSUE TITLE
QuTiP installation test -  FAILED test power-gmres

### ISSUE THREAD

**Issue by stelakus** [qutip/qutip#1750] opened 2022-01-04 20:01 UTC
I managed to successfully install QuTiP in conda, however, installation verification resulted in a FAILED test: test_steadystate.py::test_driven_cavity_power_gmres - Exception: power-gmres failed to find solution in 1000 iterations

Instead of getting a test report I also got an infinite loop returning what you can see on the image below.

I installed qutip using:
```
conda config --append channels conda-forge
conda install qutip

import qutip.testing
qutip.testing.run()

```
Any ideas why this would happen?
Any tips will be highly appreciated:)
![imagen](https://user-images.githubusercontent.com/85493516/148128436-33f94558-327e-4bed-a921-7bff732bc5d5.png)

**Comment by hodgestar** [comment] 2022-01-05 13:34
Hello! Thank you for reporting the bug. This looks like it is the same bug posted to the mailing list, so let's combine discussion here.

Running the same conda install and Python commands works for me, so we will need to dig a bit more.

If you're using MKL and numpy 1.21.X it's possible that you're encountering this numpy bug https://github.com/numpy/numpy/issues/20356. It only occurs on certain Intel CPUs (those with AVX512 CPU extensions). I believe it is fixed in numpy 1.22, but I haven't had a chance to confirm that yet.

If so, a quick solution is to try "conda install nomkl qutip" and confirm that that installs a no-MKL Blas and that the tests pass afterwards.

If not, could you post the output of `qutip.abut()` in a comment here and I can try make some more suggestions.

**Comment by Gerb0ise** [comment] 2022-01-05 14:25
Hi! I tried running `conda install nomkl qutip` and then ran the test. I can confirm it solved the issue. I doubt it is a good permanent solution though. Would you recommend reverting back to KML and upgrading numpy to 1.22?

**Comment by hodgestar** [comment] 2022-01-05 14:29
Running without MKL will be a bit slower in many cases but should otherwise work fine. If you can try upgrading to numpy 1.22 and checking that the tests pass for you, that would be great!

**Comment by stelakus** [comment] 2022-01-05 14:38
Thank you for looking into this issue. I tried doing as instructed but it doesn't seem to be able to execute the command succesfully. This has been running for 30min now:
![imagen](https://user-images.githubusercontent.com/85493516/148235603-f69bf0f7-6f69-4eac-8479-863ab7aa3872.png)

Below here my qutip.about()

`QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman and Simon Cross.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.6.2
Numpy Version:      1.20.3
Scipy Version:      1.7.1
Cython Version:     0.29.24
Matplotlib Version: 3.4.3
Python Version:     3.9.7
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\Stela Kusar\anaconda3\lib\site-packages\qutip`

**Comment by Gerb0ise** [comment] 2022-01-05 16:26
I reactivated MKL, updated numpy to 1.22.0 and when running `import qutip.testing` I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\qutip\__init__.py", line 73, in <module>
    (_blas_info() == "OPENBLAS" and platform.system() == 'Darwin')
  File "C:\ProgramData\Miniconda3\lib\site-packages\qutip\utilities.py", line 430, in _blas_info
    blas_info = config.blas_opt_info
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'`

Then as I wanted to provide my config I typed `import qutip` but it yielded the exact same error.

**Comment by hodgestar** [comment] 2022-01-05 19:55
@Gerb0ise The `no attribute 'blas_opt_info'` error is from a change in numpy 1.22 the broke qutip. After you found it it was also reported in #1753 and fixed in #1752. It will be released in 4.6.3 but that will likely only be next week, so for now reverting to numpy 1.20.3 might be the correct solution.

BLAS is OPENBLAS now because of the `nomkl` used previously. You can switch blas implementations back to MKL with `conda install "libblas=*=*mkl"` (see https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation).

**Comment by hodgestar** [comment] 2022-01-05 20:03
@stelakus It's odd that `conda install nomkl qutip` is hanging when `conda install qutip` succeeded. I don't use Windows much myself. Other options are to try downgrade numpy to 1.20.3 perhaps. Or to see what other BLAS implementations are supported in your conda environment and try explicitly install one of those. If you can get more information on why the install is hanging (maybe with `conda install -vvv ...`) I might be able to make more suggestions.

Aside: You seem to be running in your `base` conda environment. That is probably not a good idea -- create a new environment for each project you work on so that the `base` environment remains pristine.

**Comment by stelakus** [comment] 2022-01-06 08:39
Thank you for all the info @hodgestar! I reinstalled qutip in a new environment as you advise and then `conda install nomkl qutip` worked as expected. It resulted now in passing all tests (skipping a few) so I think it's best to leave it as it is for now since @Gerb0ise did not have more success upgrading numpy separately.
This is my current `qutip.about()`
```
QuTiP Version:      4.6.2
Numpy Version:      1.22.0
Scipy Version:      1.7.3
Cython Version:     0.29.25
Matplotlib Version: 3.5.0
Python Version:     3.9.7
Number of CPUs:     4
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\Stela Kusar\anaconda3\envs\qutip-env\lib\site-packages\qutip
```

**Comment by hodgestar** [comment] 2022-01-06 09:31
@stelakus Thank you for reporting back & really glad everything is working now. I'm going to leave this bug open until 4.6.3 is released so that anyone else who is tripped up by these issues can find the workarounds here.

**Comment by hodgestar** [comment] 2023-12-14 22:51
QuTiP 4.6.3 has been released some time ago. :)

**Closed by hodgestar** 2023-12-14 22:51 UTC
