### ISSUE TITLE
Installation on OS X with Homebrew script error

### ISSUE THREAD

**Issue by jhwilson** [qutip/qutip#348] opened 2015-06-18 06:41 UTC
The installation seems to succeed, but there seems to be a problem when the tests are run (or when I go into python, trying to load anything like `from qutip import *` gives an error.

The script gives the following error (which can be reproduced by just running `import qutip.testing as qt` in python):

    [. . .]
    Successfully installed qutip-3.1.0
    Running QuTiP unit tests
    /Users/justin/.pyxbld/temp.macosx-10.10-x86_64-2.7/pyrex/qutip/cy/spmatfuncs.c:250:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    /Users/justin/.pyxbld/temp.macosx-10.10-x86_64-2.7/pyrex/qutip/cy/spmatfuncs.c:250:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    /Users/justin/.pyxbld/temp.macosx-10.10-x86_64-2.7/pyrex/qutip/cy/spmatfuncs.c:250:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/qutip/__init__.py", line 213, in <module>
        from qutip.qobj import *
      File "/usr/local/lib/python2.7/site-packages/qutip/qobj.py", line 60, in <module>
        from qutip.ptrace import _ptrace
      File "/usr/local/lib/python2.7/site-packages/qutip/ptrace.py", line 38, in <module>
        from qutip.sparse import sp_reshape
      File "/usr/local/lib/python2.7/site-packages/qutip/sparse.py", line 49, in <module>
        from qutip.cy.sparse_utils import (_sparse_profile, _sparse_permute,
      File "/usr/local/lib/python2.7/site-packages/qutip/cy/__init__.py", line 1, in <module>
        from qutip.cy.spmatfuncs import *
      File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 431, in load_module
        language_level=self.language_level)
      File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
        inplace=build_inplace, language_level=language_level)
      File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 186, in build_module
        reload_support=pyxargs.reload_support)
      File "/usr/local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 100, in pyx_to_dll
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
        _build_ext.build_ext.run(self)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 171, in build_extensions
        self.build_extension(ext)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
        depends=ext.depends)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
        raise CompileError, msg
    ImportError: Building module qutip.cy.spmatfuncs failed: ["CompileError: command 'clang' failed with exit status 1\n"]
    Your system is ready to brew.

**Comment by nonhermitian** [comment] 2015-06-18 07:03
Yes, there is is some issue where the Cython compiler can not find the NumPy array header file.  This occurs only with HomeBrew and I am looking into it.

**Comment by jhwilson** [comment] 2015-06-18 17:51
I don't know if this is helpful, but I can get a different error if I first `import numpy`:

    >>> import numpy
    >>> import qutip.testing as qt
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/qutip/__init__.py", line 62, in <module>
        qutip.settings.ipython = False
    AttributeError: 'module' object has no attribute 'settings'

**Comment by nonhermitian** [comment] 2015-06-19 02:32
I can not reproduce the second error that you mention.  In addition, it seems that the error with homebrew is not a QuTiP issue, but rather some issue with the build_ext command used there. I am not 100% what the error is, but the include file directory does not seem to be passed to the compiler.

**Comment by nonhermitian** [comment] 2015-06-19 03:34
Installation using MacPorts and Anaconda (without the Fortran mcsolver) both work fine on OSX.  I would recommend using one of those.

**Comment by nonhermitian** [comment] 2015-06-22 06:07
As this is not a QuTiP issue, I will close this.  However, it seems that we should not include the Home Brew installation scripts in the next release.  In principle, there is nothing that prevents the user from obtaining the same packages as the script manually if they still wanted to use Home Brew.

**Closed by nonhermitian** 2015-06-22 06:07 UTC
Labels: question

**Comment by Nevensky** [comment] 2015-11-12 20:38
I am not so sure about it not being a QuTIP issues, this doesn't seem to happen with other modules (also installed with homebrew) requiring numpy/arrayobject.h....

**Comment by rharper2** [comment] 2016-01-18 23:48
I have just had the same problem, (I installed additional stuff with home-brew and it broke qutip).

As a complete hack workaround I noticed that DistUtil was passing to the qutip cython builder only (in my case) 
`/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7`
whereas numpy was returning 
`np.get_include() ->  /usr/local/lib/python2.7/site-packages/numpy/core/include`

For some reason this is not being passed in properly by qutip's setup.py.

Rather than dig any further I just did..

`ln -s /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7/numpy`

So I could get on with things.

**Comment by sahmed95** [comment] 2016-11-30 00:28
Hi @nonhermitian, I spent some time struggling with this as I recently shifted to macOS. This problem affects other Python installations too. I found a solution to this and if you could update it in the docs instead of the default macOS installation script, then it would be very helpful for new users. I will post the solution first and explain it below. 

1. Install a manual Python version which overrides the default Python supplied by Apple in the `usr/bin/python` path. You can check this using ```which python```. Installing using brew - 

```brew install python```

2. Change the default Python interpreter from the one supplied by macOS in `usr/bin/python` to the user installed version in `/usr/local/bin/python`. This is explained in this [post](http://blog.manbolo.com/2014/09/27/use-python-effectively-on-os-x#p1). Edit the file `/etc/paths` using ```sudo vi etc/paths``` and move the line `/usr/local/bin` to the top. This makes the user installed Python default and the packages installed by pip or brew are imported instead of the ones supplied by apple. Restart the terminal. You may need to update numpy and scipy using ```pip install numpy``` or ```pip install numpy -U```

3. Install qutip using ```python setup.py install```


Apple has its own Python version and a few modules such as numpy and scipy come along with it which are at `/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7`. These modules are difficult to manage and update due to issues with permission. Hence, even if you update numpy or scipy using `pip` or `brew`, it is not detected by Python. This also raises an issue later `error: could not create 'build/src.macosx-10.12-x86_64-2.7': Permission denied`

This solution seems better since it does not mess with the system default.

**Comment by sahmed95** [comment] 2016-11-30 00:57
I am now trying to setup a developement environment using ```python setup.py develop``` and ```python setup.py build_ext --inplace``` but getting the error 

```
cy/stochastic.pyx: cannot find cimported module 'qutip.cy.spmatfuncs'
Appending qutip.cy configuration to qutip
Ignoring attempt to set 'name' (from 'qutip' to 'qutip.cy')
Appending qutip.control configuration to qutip
Ignoring attempt to set 'name' (from 'qutip' to 'qutip.control')
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    setup(**configuration(top_path='').todict())
  File "setup.py", line 10, in configuration
    if os.environ['FORTRAN_LIBS'] == 'TRUE':
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'FORTRAN_LIBS'
```
I have gcc and gfortran installed and I suspect this might also be due to some issue with the file paths. I will try to get a workaround and post soon.
