### ISSUE TITLE
Fidelity greater than one

### ISSUE THREAD

**Issue by dick-t** [qutip/qutip#361] opened 2015-08-26 04:11 UTC
fidelity() returns >1 by a significant amount for certain pure states. States are normalised, and taking the inner product returns 1. Code below provides two examples of states which give fidelity >1 with themselves.

```
#to test qutip's fidelity routine
import qutip as qu

psi0=qu.Qobj()

i=0
while i<=1:
    j=0
    while j<=1:
        psi0+=qu.state_number_qobj([2,2],[i,j]) #even superposition of qubit states
        j+=1
    i+=1

psi0=psi0.unit() #normalise

print(qu.fidelity(psi0,psi0))
print((psi0.dag()*psi0).norm()**2)
print("\n")

psi0=qu.tensor(psi0,qu.basis(10,1)) #tensor product with Fock state

print(qu.fidelity(psi0,psi0))
print((psi0.dag()*psi0).norm()**2)

```

Output:

```
1.00000002107
1.0


1.00000003485
1.0
```

**Comment by cgranade** [comment] 2015-08-26 04:23
I suspect this is because of ``A.sqrtm()``, which is not necessary for a pure state. I'll go on and try to see what I can do with it.

**Comment by nonhermitian** [comment] 2015-08-26 05:00
There is numerical error in the answer due to the need for the sqrtm method. I am not sure if I would call this error significant as the error is of order 1e-7, while the fidelity is of order unity. However, as Chris said, there might be a better way for pure states.

Paul

**Comment by cgranade** [comment] 2015-08-26 05:05
I went on and gave a stab at it (PR #362), as it turns out we don't need ``sqrtm(sqrtm(A) * B * sqrtm(A))``  even for mixed ``A`` and ``B``--- we only need the trace of the outer ``sqrtm``, which can be done by looking at the eigenenergies directly. After informal checking, this resulted in more precise answers when F = 1. I also added more checks to make sure that the fidelity is bounded by [0, 1] to within 1e-7.

**Comment by ajgpitch** [comment] 2015-08-26 09:47
@cgranade did you test your PR #362 against dick-t example? If so what were the results?
It would seem that dick-t is comparing a method that works with states in general (mixed or pure) with one that assumes states are pure. Do we have some method in qutip that gives the fidelity when states are assumed pure? It would seem more efficient (and less numerical error risk) to compute the fidelity without the sqrtm (as dick-t did in the comparison) if we knew the states were pure.

**Comment by cgranade** [comment] 2015-08-26 09:56
When I ran against @dick-t's example, it still violated the bound F ≤ 1, but by significantly less than before, as can be confirmed by the [success of ``test_fidelity_bounded_purepure``](https://github.com/qutip/qutip/pull/362/files#diff-3e3c19be6d013d22c4823607e07cd240R106), introduced by #362. That PR doesn't fully adapt to the pure vs pure case that @dick-t lists, but it does avoid ``sqrtm`` in that case. I can fully specialize to that case, if you like, by using the inner product of the two pure states.

**Comment by ajgpitch** [comment] 2015-08-26 10:12
Having looked at the description of the function, that is it specifically refers to density matrices, then I would say that it does what it promises to do, and that the changes mean that it does it much better. So (now) personally I don't think we need to adapt for a pure vs pure state in this method.

**Comment by cgranade** [comment] 2015-08-30 11:55
With the new fidelity implementation, the numerical precision seems improved enough that I think we can mark this issue as being fixed now. Thank you for reporting this!

**Closed** 2015-08-30 11:54 UTC
