### ISSUE TITLE
tlist overridden when not providing state0 in _correlation_me_2t

### ISSUE THREAD

**Issue by VolodyaCO** [qutip/qutip#1566] opened 2021-06-05 22:25 UTC
**Describe the bug**
I want to compute the 2op_2t correlation function for a problem that I have. The documentation says that the steady state will be computed if I pass `state0=None`. In the source code, whenever this is passed, the time list `tlist` gets overridden to `[0]`. No warnings or messages are shown to the user that whatever previous `tlist` the user passed is being overridden. I think either a warning or the possibility that the list is not overridden should be the default behaviour.

**To Reproduce**
Please provide a minimal working example. For instance:

```python
from qutip import *
from qutip.steadystate import steadystate
from qutip.correlation import correlation_2op_2t
import numpy as np

H = 2 * np.pi * 0.1 * sigmax()

c1 = correlation_2op_2t(
        H,
        state0=None,
        tlist = [0, 0.1],
        taulist = [0],
        c_ops=[sigmay()],
        a_op=sigmaz(),
        b_op=sigmax(),
)

ss = steadystate(H, [sigmay()])
c2 = correlation_2op_2t(
        H,
        state0=ss,
        tlist = [0, 0.1],
        taulist = [0],
        c_ops=[sigmay()],
        a_op=sigmaz(),
        b_op=sigmax(),
)
print(c1)
print(c2)
```
The terminal out put is
```
[[0.+0.j]]
[[0.+0.j]
 [0.+0.j]]
```

**Expected behavior**
`c1` and `c2` should be the same.

**Your Environment**
```zsh
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li and Jake Lishman.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.6.0
Numpy Version:      1.20.2
Scipy Version:      1.6.3
Cython Version:     None
Matplotlib Version: 3.4.1
Python Version:     3.8.5
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /home/vladimir/.local/share/virtualenvs/phonon-bundles-5Sbweyp4/lib/python3.8/site-packages/qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

**Additional context**
This is easy to solve, I can open a PR. I've also noticed that some 1t correlation functions have t and tau defined in the documentation, but t should be 0 instead.

**Comment by AGaliciaMartinez** [comment] 2021-06-09 09:18
Hi @VolodyaCO,  thanks for reporting this!
I think the reason for `tlist` being overridden is because the result will be independent of `tlist` when the input is a steady-state. This can be seen in the following equations:
![image](https://user-images.githubusercontent.com/57414022/121327018-5d313680-c913-11eb-9760-ca6004daca18.png)
where rho is the initial state (`state0`) and H is the Hamiltonian of the system. I use the fact that rho is a steady-state to remove its temporal dependence. This derivation is simplified assuming unitary evolution (no collapse operators) but the same applies in the most general case where we include the collapse operators. This is my guess on why `tlist=[0]` is employed when using `state0=None`: the result does not depend on `tlist`. Hence, this is probably not a bug as the result should be mathematically correct.

That being said, I would also expect the same output shape for the cases shown above unless explicitly mentioned in the docstring of the function. Thus, I think the way to go here is to document this behaviour in the docstring (as well as removing the t appearing in correlation_..._1t docstring) as any change in the output shape will break backwards compatibility. However, it may be worth considering whether this is the intended behaviour for QuTiP 5. I would suggest removing `state0=None` as possible input for simplicity in the maintenance and testing or at least I would make the example shown by @VolodyaCO to be consistent and have the same output.

Let us see what the QuTiP admin team thinks :smile:

**Comment by hodgestar** [comment] 2021-06-09 11:26
This appears to already be the document behaviour, see https://qutip.org/docs/latest/apidoc/functions.html#qutip.correlation.correlation_2op_2t:

> tlist: array_like
>    list of times for t. tlist must be positive and contain the element 0. **When taking steady-steady
>    correlations only one tlist value is necessary, i.e. when t → ∞; here tlist is automatically set, ignoring user input.**

Perhaps the documentation could be made more clear, but I don't think we should change the behaviour without a compelling reason since other QuTiP users may rely on it, and it seems sensible to return only a single result in the steady state case.

**Comment by hodgestar** [comment] 2021-06-09 11:27
Closing this issue for now, but please feel free to comment or reopen if you'd like to discuss it further.

**Closed by hodgestar** 2021-06-09 11:27 UTC
Labels: BUG
