### ISSUE TITLE
Error with use_precond when using steady state solver

### ISSUE THREAD

**Issue by JetSethi** [qutip/qutip#1015] opened 2019-06-11 15:14 UTC
I am new to Qutip and I installed 4.3.1, and I was just trying to run the steady state solvers optomechanical script that was on Qutip's example notebooks. Running the cell "Run Steady State Solvers" Gives me this error:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-14-e1b88270a1b6> in <module>
      8         use_rcm = False
      9     rho_ss, info = steadystate(H, c_ops, method=ss, use_precond=True, 
---> 10                 use_rcm=use_rcm, tol=1e-15, return_info=True)
     11     print(ss,'solution time =',info['solution_time'])
     12     rho_mech = ptrace(rho_ss, 1)

/anaconda3/lib/python3.6/site-packages/qutip/steadystate.py in steadystate(A, c_op_list, method, solver, **kwargs)
    271         else:
    272             raise Exception(
--> 273                 "Invalid keyword argument '"+key+"' passed to steadystate.")
    274 
    275     # Set column perm to NATURAL if using RCM and not specified by user

Exception: Invalid keyword argument 'use_precond' passed to steadystate.

and I cannot seem to get around it. I am not sure why its not working, I tried to install 4.3.0 instead and it still did not function. It runs if I comment out the use_precond but I am not sure why its giving me this error and how to proceed from here.

**Comment by Ericgig** [comment] 2019-06-12 21:05
Duplicate of #1017

**Closed by Ericgig** 2019-06-12 21:05 UTC
