### ISSUE TITLE
AttributeError: partially initialized module 'qutip' has no attribute 'settings' (most likely due to a circular import)

### ISSUE THREAD

**Issue by akhil21** [qutip/qutip#1396] opened 2020-12-01 06:52 UTC
I installed qutip through Anaconda on MacBook M1. The installation was successful but when I tried to verify the installation through `from qutip import *`, I received following error:
`Traceback (most recent call last):
  File "/Users/akhil/opt/anaconda3/lib/python3.8/site-packages/qutip/__init__.py", line 46, in <module>
    __IPYTHON__
NameError: name '__IPYTHON__' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akhil/opt/anaconda3/lib/python3.8/site-packages/qutip/__init__.py", line 49, in <module>
    qutip.settings.ipython = False
AttributeError: partially initialized module 'qutip' has no attribute 'settings' (most likely due to a circular import)`

**Comment by jakelishman** [comment] 2020-12-01 12:17
As I understand it, the new Mac M1 chips have an ARM-based architecture so there shouldn't be any compatible binary releases on conda yet for macos - I'm surprised conda even claimed to have solved the system.  Maybe they've not updated to take the new chips into account either.

If you can, you might want to try building from source - you'll also need the Python package Cython, but this way should build all the binary components for your architecture.  We know (#1395) that there's a minor problem with some hardware detection on the M1 macs at the moment, but you can comment out lines 48 and 49 of `qutip/hardware_info.py` to work around it.

None of us have one of the new macs, and I think we'll need a new release to get conda-forge updated.  It might be a little while before we get that done, sorry.

**Comment by tinatn29** [comment] 2021-01-13 20:53
I'm also using Anaconda on Macbook M1 and ran into 2 errors today when importing qutip. 

1. With the M1 chip, qutip had a problem with hardware detection and as @jakelishman said, commenting lines 48 and 49 on `qutip/hardware_info.py` fixed this error.

2. Then I got the same error message with "IPYTHON not defined" and "'qutip' has no attribute 'settings'." I thought my conda environment must have been missing the ipython package somehow(?) so I tried `conda install ipython` and importing qutip again and it worked! (I then ran qutip.testing.run() to test out all functions and everything worked perfectly).

**Comment by MrBenGriffin** [comment] 2021-02-10 13:23
> As I understand it, the new Mac M1 chips have an ARM-based architecture so there shouldn't be any compatible binary releases on conda yet for macos - I'm surprised conda even claimed to have solved the system. Maybe they've not updated to take the new chips into account either.
> 
> If you can, you might want to try building from source - you'll also need the Python package Cython, but this way should build all the binary components for your architecture. We know (#1395) that there's a minor problem with some hardware detection on the M1 macs at the moment, but you can comment out lines 48 and 49 of `qutip/hardware_info.py` to work around it.
> 
> None of us have one of the new macs, and I think we'll need a new release to get conda-forge updated. It might be a little while before we get that done, sorry.

I have the same error on an Intel Mac (11.2.1) having installed pyqtgraph within PyCharm.

```
Connected to pydev debugger (build 203.7148.72)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ben/Library/Application Support/JetBrains/PyCharm2020.3/scratches/pyqtgraph.py", line 3, in <module>
    pg.mkQApp()
AttributeError: partially initialized module 'pyqtgraph' has no attribute 'mkQApp' (most likely due to a circular import)

```

**Comment by thangleiter** [comment] 2021-02-11 14:52
I get the same issue on a [Travis CI build](https://travis-ci.org/github/qutech/filter_functions/jobs/757061484) with
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
running on `amd64` with `qutip-4.5.2` installed via `pip`.

The same test config runs fine on Python 3.6 and 3.7, though.

**Comment by jakelishman** [comment] 2021-02-11 15:08
@thangleiter: this particular error looks possibly like it's caused by build incompatibility with the recently released numpy 1.20.  I see that the environment is installing numpy 1.19, but I suspect that the build_wheels action of `pip install` is pulling in numpy 1.20.  QuTiP 4.5 doesn't officially support installation from `pip` (we never had enough free CI available to build wheels) - you should be able to always get a working installation using the `conda-forge` channel of `conda`.  We should have wheels in the next major release.

We're currently facing a couple of problems with numpy 1.20 (#1433), but we'll be able to put out a patch when someone has time, which will include pinning numpy to a lower version when building.

**Comment by thangleiter** [comment] 2021-02-11 18:43
Unfortunately I have had some issues with `conda` in CI (for instance, it's solver uses quite a bit of memory, which had readthedocs actually shoot it down when solving the environment at some point). Also build matrices that test various combinations of optional dependencies are much cleaner when using a pure `pip` setup.

I see your point though. I'll have to work around it for now. Thanks anyway!

**Comment by jakelishman** [comment] 2021-02-21 17:01
As of the release of 4.5.3 the numpy 1.20 problems should have been fixed (including fixing the correct build versions when installing from `pip`), and all currently known problems with M1 Macs are solved on `master` with the merge of #1401.  Closing this for now.

**Closed by jakelishman** 2021-02-21 17:01 UTC
Labels: BUG

**Comment by Akhikar** [comment] 2022-08-19 04:57
AttributeError                            Traceback (most recent call last)
<ipython-input-2-82c62ef8635d> in <module>
----> 1 from qutip import *
When I try to run 
from qutip import *

I got this error. Can anyone help to come out of this error?


~/anaconda3/lib/python3.8/site-packages/qutip/__init__.py in <module>
     42 try:
     43     __IPYTHON__
---> 44     qutip.settings.ipython = True
     45 except NameError:
     46     qutip.settings.ipython = False

AttributeError: partially initialized module 'qutip' has no attribute 'settings' (most likely due to a circular import)

**Comment by hodgestar** [comment] 2022-08-19 08:43
@Akhikar I know the error message is the same, but could you open a new issue for this and follow the issue template? This bug was addressed awhile ago, and if you open a new issue we'll know what versions of all the installed software you're using.

Usually this issue arises when something went wrong while installing QuTiP, or because you have a script whose name conflicts with an existing package name.
