### ISSUE TITLE
Some tests fail on Apple M1

### ISSUE THREAD

**Issue by matteoacrossi** [qutip/qutip#1755] opened 2022-01-07 09:43 UTC
### Bug Description

Some tests of qutip.testing.run() fail on master on a MacBook Pro (2021) with M1. Qutip was installed on a miniforge python 3.9.9 distribution.

### Code to Reproduce the Bug

```shell
import qutip.testing
qutip.testing.run()
```

### Code Output

```shell
============================================================================================= FAILURES ==============================================================================================
_________________________________________________________________________________________ test_dqd_current __________________________________________________________________________________________

    def test_dqd_current():
        "Counting statistics: current and current noise in a DQD model"
    
        G = 0
        L = 1
        R = 2
    
        sz = qutip.projection(3, L, L) - qutip.projection(3, R, R)
        sx = qutip.projection(3, L, R) + qutip.projection(3, R, L)
        sR = qutip.projection(3, G, R)
        sL = qutip.projection(3, G, L)
    
        w0 = 1
        tc = 0.6 * w0
        GammaR = 0.0075 * w0
        GammaL = 0.0075 * w0
        nth = 0.00
        eps_vec = np.linspace(-1.5*w0, 1.5*w0, 20)
    
        J_ops = [GammaR * qutip.sprepost(sR, sR.dag())]
    
        c_ops = [np.sqrt(GammaR * (1 + nth)) * sR,
                 np.sqrt(GammaR * (nth)) * sR.dag(),
                 np.sqrt(GammaL * (nth)) * sL,
                 np.sqrt(GammaL * (1 + nth)) * sL.dag()]
    
        current = np.zeros(len(eps_vec))
        noise = np.zeros(len(eps_vec))
    
        for n, eps in enumerate(eps_vec):
            H = (eps/2 * sz + tc * sx)
            L = qutip.liouvillian(H, c_ops)
            rhoss = qutip.steadystate(L)
            current[n], noise[n] = qutip.countstat_current_noise(L, [],
                                                                 rhoss=rhoss,
                                                                 J_ops=J_ops)
    
            current2 = qutip.countstat_current(L, rhoss=rhoss, J_ops=J_ops)
            assert abs(current[n] - current2) < 1e-8
    
            current2 = qutip.countstat_current(L, c_ops, J_ops=J_ops)
            assert abs(current[n] - current2) < 1e-8
    
        current_target = (tc**2 * GammaR
                          / (tc**2 * (2+GammaR/GammaL) + GammaR**2/4 + eps_vec**2))
        noise_target = current_target * (
            1 - (8*GammaL*tc**2*(4 * eps_vec**2 * (GammaR - GammaL)
                                 + GammaR*(3*GammaL*GammaR + GammaR**2 + 8*tc**2))
                 / (4*tc**2*(2*GammaL + GammaR) + GammaL*GammaR**2
                    + 4*eps_vec**2*GammaL)**2)
        )
    
        np.testing.assert_allclose(current, current_target, atol=1e-4)
>       np.testing.assert_allclose(noise, noise_target, atol=1e-4)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0.0001
E       
E       Mismatched elements: 1 / 20 (5%)
E       Max absolute difference: 0.01597663
E       Max relative difference: 11.81715334
E        x: array([0.000773, 0.000879, 0.000996, 0.001121, 0.001245, 0.001352,
E              0.001422, 0.001443, 0.001422, 0.001393, 0.001393, 0.001422,
E              0.001443, 0.001422, 0.017329, 0.001245, 0.001121, 0.000996,
E              0.000879, 0.000773])
E        y: array([0.000773, 0.000879, 0.000996, 0.001121, 0.001245, 0.001352,
E              0.001422, 0.001443, 0.001422, 0.001393, 0.001393, 0.001422,
E              0.001443, 0.001422, 0.001352, 0.001245, 0.001121, 0.000996,
E              0.000879, 0.000773])

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/tests/test_countstat.py:58: AssertionError
_________________________________________________________________________ test_scheduling_gates3[circuit2 ALAP no shuffle] __________________________________________________________________________

circuit = <qutip.qip.circuit.QubitCircuit object at 0x12c081640>, method = 'ALAP', expected_length = 5, random_shuffle = False, gates_schedule = False

    @pytest.mark.parametrize(
        "circuit, method, expected_length, random_shuffle, gates_schedule",
        [
            pytest.param(deepcopy(_circuit2()), "ALAP", 5, False, False, id="circuit2 ALAP no shuffle")
        ])
    def test_scheduling_gates3(
            circuit, method, expected_length, random_shuffle, gates_schedule):
        if random_shuffle:
            repeat_num = 5
        else:
            repeat_num = 0
        result0 = gate_sequence_product(circuit.propagators())
    
        # run the scheduler
        scheduler = Scheduler(method)
        gate_cycle_indices = scheduler.schedule(
            circuit, gates_schedule=gates_schedule, repeat_num=repeat_num)
    
        # check if the scheduled length is expected
>       assert(max(gate_cycle_indices) == expected_length)
E       assert 4 == 5
E         +4
E         -5

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/tests/test_scheduler.py:143: AssertionError
__________________________________________________________________________________ test_driven_cavity[power-gmres] __________________________________________________________________________________

method = 'power-gmres', kwargs = {'M': <900x900 _CustomLinearOperator with dtype=complex128>, 'mtol': 0.1, 'use_precond': 1}

    @pytest.mark.parametrize(['method', 'kwargs'], [
        pytest.param('direct', {}, id="direct"),
        pytest.param('direct', {'sparse':False}, id="direct_dense"),
        pytest.param('eigen', {}, id="eigen"),
        pytest.param('svd', {}, id="svd"),
        pytest.param('power', {'mtol':1e-5}, id="power"),
        pytest.param('power-gmres', {'mtol':1e-1, 'use_precond':1, 'M':'iterative'},
                     id="power-gmres"),
        pytest.param('power-bicgstab', {'use_precond':1, 'M':'power'},
                     id="power-bicgstab"),
        pytest.param('iterative-gmres', {}, id="iterative-gmres"),
        pytest.param('iterative-bicgstab', {}, id="iterative-bicgstab"),
    ])
    def test_driven_cavity(method, kwargs):
        N = 30
        Omega = 0.01 * 2 * np.pi
        Gamma = 0.05
    
        a = qutip.destroy(N)
        H = Omega * (a.dag() + a)
        c_ops = [np.sqrt(Gamma) * a]
        if 'use_precond' in kwargs:
>           kwargs['M'] = qutip.build_preconditioner(H, c_ops, method=kwargs['M'])

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/tests/test_steadystate.py:124: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

A = Quantum object: dims = [[30], [30]], shape = (30, 30), type = oper, isherm = True
Qobj data =
[[0.         0.06283185 ...   0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.33835988 0.        ]]
c_op_list = [Quantum object: dims = [[30], [30]], shape = (30, 30), type = oper, isherm = False
Qobj data =
[[0.         0.2236068...  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]]]
kwargs = {'method': <900x900 _CustomLinearOperator with dtype=complex128>}, ss_args = {'ILU_MILU': 'smilu_2', 'M': None, 'all_states': False, 'diag_pivot_thresh': None, ...}, key = 'method'
L = Quantum object: dims = [[[30], [30]], [[30], [30]]], shape = (900, 900), type = super, isherm = False
Qobj data =
[[ 0....   +0.j          0.   +0.j          0.   +0.j         ...
   0.   +0.j          0.   -0.33835988j -1.45 +0.j        ]]
n = 30

    def build_preconditioner(A, c_op_list=[], **kwargs):
        """Constructs a iLU preconditioner necessary for solving for
        the steady state density matrix using the iterative linear solvers
        in the 'steadystate' function.
    
        Parameters
        ----------
        A : qobj
            A Hamiltonian or Liouvillian operator.
    
        c_op_list : list
            A list of collapse operators.
    
        return_info : bool, optional, default = False
            Return a dictionary of solver-specific infomation about the
            solution and how it was obtained.
    
        use_rcm : bool, optional, default = False
            Use reverse Cuthill-Mckee reordering to minimize fill-in in the
            LU factorization of the Liouvillian.
    
        use_wbm : bool, optional, default = False
            Use Weighted Bipartite Matching reordering to make the Liouvillian
            diagonally dominant.  This is useful for iterative preconditioners
            only, and is set to ``True`` by default when finding a preconditioner.
    
        weight : float, optional
            Sets the size of the elements used for adding the unity trace condition
            to the linear solvers.  This is set to the average abs value of the
            Liouvillian elements if not specified by the user.
    
        method : str, default = 'iterative'
            Tells the preconditioner what type of Liouvillian to build for
            iLU factorization.  For direct iterative methods use 'iterative'.
            For power iterative methods use 'power'.
    
        permc_spec : str, optional, default='COLAMD'
            Column ordering used internally by superLU for the
            'direct' LU decomposition method. Options include 'COLAMD' and
            'NATURAL'. If using RCM then this is set to 'NATURAL' automatically
            unless explicitly specified.
    
        fill_factor : float, optional, default = 100
            Specifies the fill ratio upper bound (>=1) of the iLU
            preconditioner.  Lower values save memory at the cost of longer
            execution times and a possible singular factorization.
    
        drop_tol : float, optional, default = 1e-4
            Sets the threshold for the magnitude of preconditioner
            elements that should be dropped.  Can be reduced for a courser
            factorization at the cost of an increased number of iterations, and a
            possible singular factorization.
    
        diag_pivot_thresh : float, optional, default = None
            Sets the threshold between [0,1] for which diagonal
            elements are considered acceptable pivot points when using a
            preconditioner.  A value of zero forces the pivot to be the diagonal
            element.
    
        ILU_MILU : str, optional, default = 'smilu_2'
            Selects the incomplete LU decomposition method algoithm used in
            creating the preconditoner. Should only be used by advanced users.
    
        Returns
        -------
        lu : object
            Returns a SuperLU object representing iLU preconditioner.
    
        info : dict, optional
            Dictionary containing solver-specific information.
        """
        ss_args = _default_steadystate_args()
        ss_args['method'] = 'iterative'
        for key in kwargs.keys():
            if key in ss_args.keys():
                ss_args[key] = kwargs[key]
            else:
                raise TypeError("Invalid keyword argument '" + key +
                                "' passed to steadystate.")
    
        # Set column perm to NATURAL if using RCM and not specified by user
        if ss_args['use_rcm'] and ('permc_spec' not in kwargs.keys()):
            ss_args['permc_spec'] = 'NATURAL'
    
        L = _steadystate_setup(A, c_op_list)
        # Set weight parameter to avg abs val in L if not set explicitly
        if 'weight' not in kwargs.keys():
            ss_args['weight'] = np.mean(np.abs(L.data.data.max()))
            ss_args['info']['weight'] = ss_args['weight']
    
        n = int(np.sqrt(L.shape[0]))
        if ss_args['method'] == 'iterative':
            ss_list = _steadystate_LU_liouvillian(L, ss_args)
            L, perm, perm2, rev_perm, ss_args = ss_list
        elif ss_args['method'] == 'power':
            ss_list = _steadystate_power_liouvillian(L, ss_args)
            L, perm, perm2, rev_perm, ss_args = ss_list
        else:
>           raise ValueError("Invalid preconditioning method.")
E           ValueError: Invalid preconditioning method.

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/steadystate.py:1109: ValueError
________________________________________________________________________________ test_driven_cavity[power-bicgstab] _________________________________________________________________________________

method = 'power-bicgstab', kwargs = {'M': <900x900 _CustomLinearOperator with dtype=complex128>, 'use_precond': 1}

    @pytest.mark.parametrize(['method', 'kwargs'], [
        pytest.param('direct', {}, id="direct"),
        pytest.param('direct', {'sparse':False}, id="direct_dense"),
        pytest.param('eigen', {}, id="eigen"),
        pytest.param('svd', {}, id="svd"),
        pytest.param('power', {'mtol':1e-5}, id="power"),
        pytest.param('power-gmres', {'mtol':1e-1, 'use_precond':1, 'M':'iterative'},
                     id="power-gmres"),
        pytest.param('power-bicgstab', {'use_precond':1, 'M':'power'},
                     id="power-bicgstab"),
        pytest.param('iterative-gmres', {}, id="iterative-gmres"),
        pytest.param('iterative-bicgstab', {}, id="iterative-bicgstab"),
    ])
    def test_driven_cavity(method, kwargs):
        N = 30
        Omega = 0.01 * 2 * np.pi
        Gamma = 0.05
    
        a = qutip.destroy(N)
        H = Omega * (a.dag() + a)
        c_ops = [np.sqrt(Gamma) * a]
        if 'use_precond' in kwargs:
>           kwargs['M'] = qutip.build_preconditioner(H, c_ops, method=kwargs['M'])

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/tests/test_steadystate.py:124: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

A = Quantum object: dims = [[30], [30]], shape = (30, 30), type = oper, isherm = True
Qobj data =
[[0.         0.06283185 ...   0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.33835988 0.        ]]
c_op_list = [Quantum object: dims = [[30], [30]], shape = (30, 30), type = oper, isherm = False
Qobj data =
[[0.         0.2236068...  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]]]
kwargs = {'method': <900x900 _CustomLinearOperator with dtype=complex128>}, ss_args = {'ILU_MILU': 'smilu_2', 'M': None, 'all_states': False, 'diag_pivot_thresh': None, ...}, key = 'method'
L = Quantum object: dims = [[[30], [30]], [[30], [30]]], shape = (900, 900), type = super, isherm = False
Qobj data =
[[ 0....   +0.j          0.   +0.j          0.   +0.j         ...
   0.   +0.j          0.   -0.33835988j -1.45 +0.j        ]]
n = 30

    def build_preconditioner(A, c_op_list=[], **kwargs):
        """Constructs a iLU preconditioner necessary for solving for
        the steady state density matrix using the iterative linear solvers
        in the 'steadystate' function.
    
        Parameters
        ----------
        A : qobj
            A Hamiltonian or Liouvillian operator.
    
        c_op_list : list
            A list of collapse operators.
    
        return_info : bool, optional, default = False
            Return a dictionary of solver-specific infomation about the
            solution and how it was obtained.
    
        use_rcm : bool, optional, default = False
            Use reverse Cuthill-Mckee reordering to minimize fill-in in the
            LU factorization of the Liouvillian.
    
        use_wbm : bool, optional, default = False
            Use Weighted Bipartite Matching reordering to make the Liouvillian
            diagonally dominant.  This is useful for iterative preconditioners
            only, and is set to ``True`` by default when finding a preconditioner.
    
        weight : float, optional
            Sets the size of the elements used for adding the unity trace condition
            to the linear solvers.  This is set to the average abs value of the
            Liouvillian elements if not specified by the user.
    
        method : str, default = 'iterative'
            Tells the preconditioner what type of Liouvillian to build for
            iLU factorization.  For direct iterative methods use 'iterative'.
            For power iterative methods use 'power'.
    
        permc_spec : str, optional, default='COLAMD'
            Column ordering used internally by superLU for the
            'direct' LU decomposition method. Options include 'COLAMD' and
            'NATURAL'. If using RCM then this is set to 'NATURAL' automatically
            unless explicitly specified.
    
        fill_factor : float, optional, default = 100
            Specifies the fill ratio upper bound (>=1) of the iLU
            preconditioner.  Lower values save memory at the cost of longer
            execution times and a possible singular factorization.
    
        drop_tol : float, optional, default = 1e-4
            Sets the threshold for the magnitude of preconditioner
            elements that should be dropped.  Can be reduced for a courser
            factorization at the cost of an increased number of iterations, and a
            possible singular factorization.
    
        diag_pivot_thresh : float, optional, default = None
            Sets the threshold between [0,1] for which diagonal
            elements are considered acceptable pivot points when using a
            preconditioner.  A value of zero forces the pivot to be the diagonal
            element.
    
        ILU_MILU : str, optional, default = 'smilu_2'
            Selects the incomplete LU decomposition method algoithm used in
            creating the preconditoner. Should only be used by advanced users.
    
        Returns
        -------
        lu : object
            Returns a SuperLU object representing iLU preconditioner.
    
        info : dict, optional
            Dictionary containing solver-specific information.
        """
        ss_args = _default_steadystate_args()
        ss_args['method'] = 'iterative'
        for key in kwargs.keys():
            if key in ss_args.keys():
                ss_args[key] = kwargs[key]
            else:
                raise TypeError("Invalid keyword argument '" + key +
                                "' passed to steadystate.")
    
        # Set column perm to NATURAL if using RCM and not specified by user
        if ss_args['use_rcm'] and ('permc_spec' not in kwargs.keys()):
            ss_args['permc_spec'] = 'NATURAL'
    
        L = _steadystate_setup(A, c_op_list)
        # Set weight parameter to avg abs val in L if not set explicitly
        if 'weight' not in kwargs.keys():
            ss_args['weight'] = np.mean(np.abs(L.data.data.max()))
            ss_args['info']['weight'] = ss_args['weight']
    
        n = int(np.sqrt(L.shape[0]))
        if ss_args['method'] == 'iterative':
            ss_list = _steadystate_LU_liouvillian(L, ss_args)
            L, perm, perm2, rev_perm, ss_args = ss_list
        elif ss_args['method'] == 'power':
            ss_list = _steadystate_power_liouvillian(L, ss_args)
            L, perm, perm2, rev_perm, ss_args = ss_list
        else:
>           raise ValueError("Invalid preconditioning method.")
E           ValueError: Invalid preconditioning method.

/opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip/steadystate.py:1109: ValueError
====================================================================================== short test summary info ======================================================================================
FAILED tests/test_countstat.py::test_dqd_current - AssertionError: 
FAILED tests/test_scheduler.py::test_scheduling_gates3[circuit2 ALAP no shuffle] - assert 4 == 5
FAILED tests/test_steadystate.py::test_driven_cavity[power-gmres] - ValueError: Invalid preconditioning method.
FAILED tests/test_steadystate.py::test_driven_cavity[power-bicgstab] - ValueError: Invalid preconditioning method.
======================================================== 4 failed, 2845 passed, 120 skipped, 67 deselected, 4 warnings in 130.89s (0:02:10) =========================================================
```

### Expected Behaviour

Tests should succeed.

### Your Environment

```shell
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman and Simon Cross.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.7.0.dev0+3ff3f42
Numpy Version:      1.20.3
Scipy Version:      1.7.3
Cython Version:     None
Matplotlib Version: None
Python Version:     3.9.9
Number of CPUs:     10
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
Installation path:  /opt/homebrew/Caskroom/miniforge/base/envs/qutip_test/lib/python3.9/site-packages/qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

**Comment by hodgestar** [comment] 2022-01-07 09:57
@matteoacrossi Thank you for running the tests and reporting these. I'm glad there are only four failing.

I can't immediately guess the cause of any of them, so some digging is needed. If you're up to digging into them I'm happy to review and merge PRs. If not, no worries -- I will try think of another plan.

**Comment by matteoacrossi** [comment] 2022-01-07 09:59
@hodgestar I'm happy to help digging into them if you instruct me! Also thanks for all the effort in getting qutip to work on M1!

**Comment by hodgestar** [comment] 2022-01-07 10:05
@matteoacrossi Thanks! I don't know that I have much particular advice, other than "let's try debug the failing tests one at a time". Maybe pick one of the `test_driven_cavity` ones, because I'm not quite sure how `ValueError: Invalid preconditioning method` can get raised when it succeeds on other platforms. Maybe it is a bug that isn't completely related to the M1?

Are you familiar with pdb? Running just the one test using pytest and `pytest --pdb` will allow to explore the stack trace and see the values of variables in each stack frame, and hopefully figure out what went wrong.

Another first step is just to fix the line `raise ValueError("Invalid preconditioning method.")` to be `raise ValueError(f"Invalid preconditioning method: {ss_args['method']!r}.")` so that the error messages gives more of a hint of what the invalid method name was.

**Comment by BoxiLi** [comment] 2022-01-07 12:24
I'm very surprised to see that there is a failing test on qutip.qip, which is pure python and is unlikely to be platform dependent.

I have a guess that that one may have something to do with pytest parameterization. I had a problem with that on Mac OS (not M1) before, which I still don't fully understand and I left a comment back then:
https://github.com/qutip/qutip/blob/3ff3f42d2cd950c99af8936b12d9221ed79de5e3/qutip/tests/test_scheduler.py#L92-L94
If I split the test and run them (`test_scheduling_gates2` and `test_scheduling_gates3`) one by one, it is fine. But if I use pytest parameterization to initialize several of them, it fails. And now this time it happens at exactly the same place.

If you would like to, you can copy that failing test and run it (without using pytest parameterization but giving the input explicitly) in a Python console. If it works well, then my guess should be right. But it doesn't apply to all other failing tests I think.

**Comment by matteoacrossi** [comment] 2022-01-07 12:32
Indeed if I run the following

```python
from qutip.tests.test_scheduler import *
from qutip.tests.test_scheduler import _circuit2

test_scheduling_gates2(deepcopy(_circuit2()), "ALAP", 5, False, False)
```

It seems to be working.

**Comment by BoxiLi** [comment] 2022-01-07 12:48
Ah great! Thanks! So I probably used parameterization with the circuit in a non-recommended way. The source code is correct, there is just something wrong with the test. I'll try coming up with a solution for that test later.

**Comment by matteoacrossi** [comment] 2022-01-07 12:58
@BoxiLi also, quite interestingly it seems that the tests don't fail all the times. This is another run of the tests:

```
FAILED tests/test_countstat.py::test_dqd_current - AssertionError: 
======================================================== 1 failed, 2872 passed, 119 skipped, 67 deselected, 67 warnings in 132.32s (0:02:12) ========================================================
```

I actually think it only happens if I use `qutip.testing.run()` more than once in the same python shell. And by running pytest directly they don't seem to fail. 

`test_countstat.py::test_dqd_current` is the only one that fails consistently.

**Comment by BoxiLi** [comment] 2022-01-07 13:10
Interesting, sounds like some cached value of the previous test corrupted the next one. Since the other two tests also use parameterization. The reason might even be the same, except for `test_countstat.py::test_dqd_current`.

**Comment by matteoacrossi** [comment] 2022-01-10 13:16
On the `test_dqd_current()` test: it appears that the problem is with the element 14 in the `eps_vec`. I did some more checking with different values for `eps_vec`, and there are other values which give problems, you can see the code below. 

I defined a function that returns the values for a given value of `eps`:

```python
def current_noise_eps(eps):
    H = (eps/2 * sz + tc * sx)
    L = qutip.liouvillian(H, c_ops)
    rhoss = qutip.steadystate(L)
    current, noise = qutip.countstat_current_noise(L, [],
                                                            rhoss=rhoss,
                                                            J_ops=J_ops)

    current2 = qutip.countstat_current(L, rhoss=rhoss, J_ops=J_ops)
    assert abs(current - current2) < 1e-8

    current2 = qutip.countstat_current(L, c_ops, J_ops=J_ops)
    assert abs(current - current2) < 1e-8

    current_target = (tc**2 * GammaR
                        / (tc**2 * (2+GammaR/GammaL) + GammaR**2/4 + eps**2))
    noise_target = current_target * (
        1 - (8*GammaL*tc**2*(4 * eps**2 * (GammaR - GammaL)
                                + GammaR*(3*GammaL*GammaR + GammaR**2 + 8*tc**2))
                / (4*tc**2*(2*GammaL + GammaR) + GammaL*GammaR**2
                + 4*eps**2*GammaL)**2)
    )

    return current.flatten()[0], current_target, noise.flatten()[0], noise_target, rhoss
```

Now I have the following:

```
>>> res = current_noise_eps(1.04)
>>> print(res[2:4])
(0.06374906663351243, 0.0011104778081249154)
```

So the `noise` is quite different from `noise_target`.

But if I increment `eps` by `1e-15` then everything is fine.

```
>>> res1 = current_noise_eps(1.04+1e-15)
>>> print(res1)
(0.0011104778081249132, 0.0011104778081249143)
```

Comparing `rhoss` in the two cases gives differences that are of the order of the increment in `eps`:

```
>>> print(res[-1].data.todense() - res1[-1].data.todense())
[[ 1.11022302e-16+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j -5.55111512e-16+0.00000000e+00j
  -1.11022302e-16+8.67361738e-19j]
 [ 0.00000000e+00+0.00000000e+00j -1.11022302e-16-8.67361738e-19j
   2.22044605e-16+0.00000000e+00j]]
```

So I think the problem is not in the `steadystate` function but it must be in `countstat_current_noise`.

**Comment by asma2farhat** [comment] 2024-03-13 08:33
> On the `test_dqd_current()` test: it appears that the problem is with the element 14 in the `eps_vec`. I did some more checking with different values for `eps_vec`, and there are other values which give problems, you can see the code below.
> 
> I defined a function that returns the values for a given value of `eps`:
> 
> ```python
> def current_noise_eps(eps):
>     H = (eps/2 * sz + tc * sx)
>     L = qutip.liouvillian(H, c_ops)
>     rhoss = qutip.steadystate(L)
>     current, noise = qutip.countstat_current_noise(L, [],
>                                                             rhoss=rhoss,
>                                                             J_ops=J_ops)
> 
>     current2 = qutip.countstat_current(L, rhoss=rhoss, J_ops=J_ops)
>     assert abs(current - current2) < 1e-8
> 
>     current2 = qutip.countstat_current(L, c_ops, J_ops=J_ops)
>     assert abs(current - current2) < 1e-8
> 
>     current_target = (tc**2 * GammaR
>                         / (tc**2 * (2+GammaR/GammaL) + GammaR**2/4 + eps**2))
>     noise_target = current_target * (
>         1 - (8*GammaL*tc**2*(4 * eps**2 * (GammaR - GammaL)
>                                 + GammaR*(3*GammaL*GammaR + GammaR**2 + 8*tc**2))
>                 / (4*tc**2*(2*GammaL + GammaR) + GammaL*GammaR**2
>                 + 4*eps**2*GammaL)**2)
>     )
> 
>     return current.flatten()[0], current_target, noise.flatten()[0], noise_target, rhoss
> ```
> 
> Now I have the following:
> 
> ```
> >>> res = current_noise_eps(1.04)
> >>> print(res[2:4])
> (0.06374906663351243, 0.0011104778081249154)
> ```
> 
> So the `noise` is quite different from `noise_target`.
> 
> But if I increment `eps` by `1e-15` then everything is fine.
> 
> ```
> >>> res1 = current_noise_eps(1.04+1e-15)
> >>> print(res1)
> (0.0011104778081249132, 0.0011104778081249143)
> ```
> 
> Comparing `rhoss` in the two cases gives differences that are of the order of the increment in `eps`:
> 
> ```
> >>> print(res[-1].data.todense() - res1[-1].data.todense())
> [[ 1.11022302e-16+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
>    0.00000000e+00+0.00000000e+00j]
>  [ 0.00000000e+00+0.00000000e+00j -5.55111512e-16+0.00000000e+00j
>   -1.11022302e-16+8.67361738e-19j]
>  [ 0.00000000e+00+0.00000000e+00j -1.11022302e-16-8.67361738e-19j
>    2.22044605e-16+0.00000000e+00j]]
> ```
> 
> So I think the problem is not in the `steadystate` function but it must be in `countstat_current_noise`.

Can someone tell me how to fix this? because I am also using mac M1, and this is the only test that keeps failing: test_countstat.py::test_dqd_current - AssertionError

**Comment by Ericgig** [comment] 2024-04-01 03:45
Fixed with v5 release.

**Closed by Ericgig** 2024-04-01 03:45 UTC
