### ISSUE TITLE
Enabling OPENMP

### ISSUE THREAD

**Issue by OChiB** [qutip/qutip#1378] opened 2020-11-06 17:26 UTC
Hello,

I'm trying to make "OPENMP Installed:   False" to "OPENMP Installed:   True", but somehow it does not work.
I have never tried to use openmp, so I am completely new to this, so maybe I did not do the right thing, which is common.
qutip.about() shows me the following things:

--------------------

QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Current admin team: Alexander Pitchford, Paul D. Nation, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, and Boxi Li
Project Manager: Franco Nori.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.2
Numpy Version:      1.18.5
Scipy Version:      1.5.3
Cython Version:     0.29.21
Matplotlib Version: 3.3.2
Python Version:     3.7.8
Number of CPUs:     6
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\***\AppData\Local\Continuum\anaconda3\lib\site-packages\qutip
==============================================================================
Please cite QuTiP in your publication.
==============================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

--------------------

What I have done so far:
- installed qutip from source following the instructions
--- the "zspmv_openmp.cpp" problem is solved
--- everything is installed without errors

- Updated all packages/spyder/python/anaconda/...

- installed Visual Studio Build Tools 2019 (2) Version 16.7.7
--- this includes "C++ Buildtools" (maybe not important, but also ".NET Desktop-Buildtools" and ".NET Core-Buuildtools"

- I checked, whether openmp is installed in anaconda powershell prompt via "conda install -c conda-forge openmp"
--- it shows "# All requested packages already installed." So it seems openmp is already installed

It would be a great help, if you give me a possible solution to this

Thanks in advance!!

**Comment by nwlambert** [comment] 2021-03-28 07:49
Sorry, this reply is very late!  I was testing openmp installs on windows the other day.  if you make a new conda environment, and make sure to install openmp first, it seems OK.  (In once instance I did seem to have your issue, but I am not exactly sure what I did to reproduce it because it suddenly disappeared. Perhaps you had qutip already installed, and then tried to reinstall on top of it with openmp enabled?).

however, you may then run into the issue currently being fixed in https://github.com/qutip/qutip/pull/1471  
You might need to wait a little for that fix to be merged, or use Jake's branch in the mean time.

**Comment by jakelishman** [comment] 2021-03-29 13:46
#1471 is now merged into `master`, so that will be included in 4.next.

To help debug this particular issue, could you post the output of `python setup.py install` (or `pip install -v`, possibly repeating the `-v` up to 3 times).  We need to see the compilation commands and compiler output that's being issued during the build process.

After that, could you _temporarily_ change this block of code in `qutip/__init__.py`: https://github.com/qutip/qutip/blob/2aaae75d3ba52067f747dd928d67d66307fc5de9/qutip/__init__.py#L100-L107
to
```python
from qutip.cy.openmp.parfuncs import spmv_csr_openmp
```
(i.e. remove the entire `try/except` block and leave the import).  This will cause QuTiP to throw an exception when you try to import it - could you also post the output of that exception?  You'll want to revert that change right after, so you have a functioning version of non-OpenMP QuTiP at the very least.

**Comment by hodgestar** [comment] 2021-08-04 13:02
The fixes in #1471 were released in 4.6.0, Neill reported that it worked for him, so I'm closing this issue for now. Please comment or reopen it if there is more to report.

**Closed by hodgestar** 2021-08-04 13:02 UTC

**Comment by sRb-root** [comment] 2021-09-10 09:39
Hi. I am having the same issue when installing through anaconda3 on Ubuntu20.04. The steps which I am following are:

$ conda create -n qutip python=3
$ conda activate qutip
$ conda install -c conda-forge openmp
$ conda install -c conda-forge qutip

However, when I execute qutip.about(), I get the following:

QuTiP Version:      4.6.2
Numpy Version:      1.20.3
Scipy Version:      1.6.3
Cython Version:     None
Matplotlib Version: None
Python Version:     3.9.6
Number of CPUs:     6
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /home/sourav/anaconda3/envs/qutip/lib/python3.9/site-packages/qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

As you can see, OPENMP does not seem to be enabled. Please let me know if I am doing things incorrectly.

**Comment by hodgestar** [comment] 2021-09-10 11:08
Hello! As @jakelishman described, you can help debug this issue by trying:

```python
from qutip.cy.openmp.parfuncs import spmv_csr_openmp
```

and reading the exception produced.

I suspect that the `qutip.cy.openmp.*` packages will simply not have been compiled -- they're only built by QuTiP when "--with-openmp" is passed to `setup.py` and I think `conda install ... qutip` will not do that even when OpenMP is already installed. To correct this you will need to install QuTiP from source and pass `--with-openmp` yourself as described in https://qutip.org/docs/latest/installation.html?highlight=openmp#direct-setuptools-source-builds.

We probably could make "openmpi" and "no-openmpi" builds for conda-forge by adapting the pattern in https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp but that would require some work (and be a feature enhancement :).
