### ISSUE TITLE
QuTiP VS RK45: Which one gives the correct results for time-dependent systems?

### ISSUE THREAD

**Issue by alipedram01** [qutip/qutip#1733] opened 2021-12-06 10:40 UTC
### Describe the Issue!

I am writing a code for a quantum thermal machine which includes both coherent and dissipative time evolutions in its different stages of operation. However, evolving the system with "mesolve" function of QuTiP (which uses either Adams or BDF methods) and Runge-Kutta gives different results. My code has time dependent Hamiltonians and collapse operators. For demonstration purposes I wrote a simple code which deals with the master equation of a time-dependent harmonic oscillator of mass and frequency equal to 1. The jump operator is the position operator times a time-dependent coefficient. 

```python
    import numpy as np
    import scipy as sp
    from qutip import *
    
    tend = 5
    tvec = np.linspace(0,tend,1000)
    ω1 = 1 #initial frequency
    ω2 = 2 #final frequency
    gamma = 1 #dissipation rate
    
    def omg_fun(t, args): #time-dependent frequency
        s = t/tend
        ω_t = ω1 + 10*(ω2-ω1)*s**3 - 15*(ω2-ω1)*s**4 + 6*(ω2-ω1)*s**5
        return ω_t
    
    def col_fun(t, args): #time dependent collapse operator coefficient
        return np.sqrt(gamma * np.exp(-t))
    
    def omg_fun_rk(t): #time-dependent frequency for RK45
        s = t/tend
        ω_t = ω1 + 10*(ω2-ω1)*s**3 - 15*(ω2-ω1)*s**4 + 6*(ω2-ω1)*s**5
        return ω_t
    
    def col_fun_rk(t):  #time dependent collapse operator coefficient for RK45
        return np.sqrt(gamma * np.exp(-t))
    
    N=10
    m = 1 #mass
    ħ = 1
    x = np.sqrt(ħ/(2*m*ω1))*(create(N)+destroy(N)) #position operator
    p = 1j*np.sqrt((ħ*m*ω1)/2)*(create(N)-destroy(N)) #momentum operator
    H = [(p**2)/(2*m), [(1/2)*m*x**2,omg_fun]]
    c_ops = [[x,col_fun]]
    rho_init = fock_dm(N,1)
    rhot_vec = mesolve(H,rho_init,tvec,c_ops)
    rhot_qutip = rhot_vec.states[-1]
    
    #Right hand side of the master equation
    def rhs(ρ,H,gamma,op):
        c_op = np.sqrt(gamma)*op
        res = -1j*(H*ρ - ρ*H)+(1/2)*(2*c_op*ρ*c_op.dag()-ρ*c_op.dag()*c_op-c_op*c_op.dag()*ρ)
        return res
    
    #Runge-Kutta Solver
    def rksolver(ρ,dt,H,gamma,op):
        k1 = rhs(ρ,H,gamma,op)
        k2 = rhs(ρ+(dt/2)*k1,H,gamma,op)
        k3 = rhs(ρ+(dt/2)*k2,H,gamma,op)
        k4 = rhs(ρ+dt*k3,H,gamma,op)
        rho = ρ+dt*(k1+2*k2+2*k3+k4)/6
        return rho
    
    dt = tvec[1]-tvec[0]
    for i in range(len(tvec)):
        H_rk = (p**2)/(2*m) + (1/2)*m*x**2*omg_fun_rk(tvec[i])
        gamma_rk = col_fun_rk(tvec[i])
        rhot_rk = rksolver(rho_init,dt,H_rk,gamma_rk,x)
        rho_init = rhot_rk
```

The fidelity of the final density matrices for these two methods is 0.9312276926316011. This question is also asked [here](https://quantumcomputing.stackexchange.com/questions/22187/qutip-vs-rk45-which-one-gives-the-correct-results-for-time-dependent-systems) and the final density matrices using these two approaches are shown. Basically the density matrices are not close enough. So the question is, which one is correct and why these two methods are giving different results?

Note: For time-independent problems and for time-dependent but coherent evolution the results agree pretty well. However for the case of time-dependent Hamiltonian and dissipation they don't.

**Comment by hodgestar** [comment] 2021-12-06 10:46
Near the start for the QuTiP case you have:
```python
c_ops = [[x,omg_fun]]
```
Should that not be
```python
c_ops = [[x,col_fun]]
```
?

**Comment by alipedram01** [comment] 2021-12-06 10:52
Thanks for the comment and sorry for the typo. I corrected it. The issue still persists. I also updated [the question](https://quantumcomputing.stackexchange.com/questions/22187/qutip-vs-rk45-which-one-gives-the-correct-results-for-time-dependent-systems) on stack exchange.

**Comment by jakelishman** [comment] 2021-12-06 10:53
Assuming Simon's point isn't just a complete answer to your question: in the general case, this is an impossible question to answer - it touches on many parts of numerical integration, such as tolerance limits and adaptive step-size methods. When you're dealing with completely arbitrary time-dependence, there's not really any one-size-fits-all approach that'll work (despite how RK45 is often taught as a magic bullet in physics courses).

Here, you will likely find that your RK45 results depend strongly on how many intermediate timesteps you use, whereas QuTiP's results will be (marginally) more stable.  This is because QuTiP will internally subdivide the timesteps more to achieve internal precision goals, but then only returns the results at the time points you ask for.  You can increase the maximum number of allowed subdivisions by increasing the `nsteps` parameter in a `qutip.Options` object, and with the `options` keyword argument.

**Comment by alipedram01** [comment] 2021-12-06 10:59
> Assuming Simon's point isn't just a complete answer to your question: in the general case, this is an impossible question to answer - it touches on many parts of numerical integration, such as tolerance limits and adaptive step-size methods. When you're dealing with completely arbitrary time-dependence, there's not really any one-size-fits-all approach that'll work (despite how RK45 is often taught as a magic bullet in physics courses).
> 
> Here, you will likely find that your RK45 results depend strongly on how many intermediate timesteps you use, whereas QuTiP's results will be (marginally) more stable. This is because QuTiP will internally subdivide the timesteps more to achieve internal precision goals, but then only returns the results at the time points you ask for. You can increase the maximum number of allowed subdivisions by increasing the `nsteps` parameter in a `qutip.Options` object, and with the `options` keyword argument.

I addressed Simon's question. Also, I tried different solver options in mesolve including solver type, nsteps, relative and absolute tolerence, etc ... Also for RK45 I tried to change the parameters in order to see if the solutions coincide. They didn't. I don't know if there exists an analytically solvable problem in which both Hamiltonian and dissipation operators are time dependent, but if there is such a problem, then I can use it as a benchmark in order to compare QuTiP and RK45.

**Comment by jakelishman** [comment] 2021-12-06 11:02
I don't want to straight up say "QuTiP is correct", because as I mentioned, the field of numerical computing is incredibly tricky, but it _probably_ is more accurate in this situation.  I just tried doing what I suggested in my previous post (increase the number of time-steps), and found QuTiP was stable, but your RK45 implementation started differing.  This is strongly suggestive that your RK45 isn't fully converging for this problem.

**Comment by alipedram01** [comment] 2021-12-06 11:21
> I don't want to straight up say "QuTiP is correct", because as I mentioned, the field of numerical computing is incredibly tricky, but it _probably_ is more accurate in this situation. I just tried doing what I suggested in my previous post (increase the number of time-steps), and found QuTiP was stable, but your RK45 implementation started differing. This is strongly suggestive that your RK45 isn't fully converging for this problem.

I don't think you are right. As I mentioned I also did the same but the results are stable. I edited [my question on quantum computing stack exchange](https://quantumcomputing.stackexchange.com/questions/22187/qutip-vs-rk45-which-one-gives-the-correct-results-for-time-dependent-systems) if you are interested. There is no convergence issue. And I don't think it is "impossible" to figure out what is causing this difference or to understand which one is closer to the actual answer. If there exists a system with time-dependent Hamiltonian under a time-dependent dissipation which is analytically solvable, we can compare these two methods. I am not aware of such a problem.

**Comment by nonhermitian** [comment] 2021-12-06 12:16
The RK45 code here has no notion of error associated with it; you have no way of saying whether a particular step size `dt` is actually good.  It ideally should converge to something as the step size goes to zero.  QuTiP has an adaptive solver that modifies the step size to keep the error below the supplied tolerances.  For time-dependent problems one could run into issues with very narrow pulses, but that is not the case here.  Writing ones own ODE solver is not really the best thing to do outside of a learning exercise for reasons along these lines.

**Comment by jakelishman** [comment] 2021-12-06 12:18
For clarity: I ran your code with 1,000 timesteps and 10,000 timesteps and found a linalg norm difference in the outputs of 4.4e-4 (compared to QuTiP's 6.5e-8), which is what I meant.  I considered that difference "not fully convergent" in part because QuTiP's default tolerance goals have an absolute tolerance of ~1e-8 (that's per-element, not the full norm).

Here's a couple more things to look at:
- if you're using QuTiP objects without our solvers like this, we tidy up sparse matrices at every operation.  You probably don't want that - you might get different results if you convert your RK method to work on raw Numpy arrays.
- your RHS isn't accurate - it takes `sqrt(gamma)`, but your time-dependent function already does that.  This is perhaps a mistake, and very likely the source of the discrepancy?  Also, while it's irrelevant here, your Lindbladian has `c_op * c_op.dag() * rho` as the last term, but it should be `c_op.dag() * c_op * rho`.
- your RK method isn't using updated versions of the Hamiltonian or the collapse operator at the intermediate timesteps.
- you say you're using RK45, but you've only got 4 different evaluations?  That looks like an RK4 method to me (not that it should matter).

**Comment by hodgestar** [comment] 2022-01-05 11:28
@alipedram01 It looks like we've understood the cause of the issue -- i.e. your RK45 solver just doesn't converge for this problem. That's probably not unexpected -- I see to remember reading on Wikipedia that the implicit Runga-Kutta methods have small regions of convergence relative to explicit or adaptive methods.

Closing this for now, but thank you for taking a look and please feel free to continue the discussion if needed.

**Closed by hodgestar** 2022-01-05 11:28 UTC
